/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* ECO_opt_2inj_cost_ext_cost_fun:(i0[6],i1[4],i2[0],i3[0])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53;
  a00=1.0000000000000000e-04;
  a01=arg[1]? arg[1][0] : 0;
  a02=casadi_sq(a01);
  a03=arg[1]? arg[1][1] : 0;
  a04=casadi_sq(a03);
  a02=(a02+a04);
  a04=arg[1]? arg[1][2] : 0;
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a05=arg[1]? arg[1][3] : 0;
  a06=casadi_sq(a05);
  a02=(a02+a06);
  a00=(a00*a02);
  a02=10.;
  a06=5.0000000000000000e-01;
  a07=2.9678653787116167e+02;
  a08=1000.;
  a09=10000000.;
  a10=arg[0]? arg[0][0] : 0;
  a09=(a09*a10);
  a10=1.0486488000000000e+05;
  a11=5.2214244335811971e-04;
  a12=3.1741935483870970e-05;
  a13=2.4600000000000002e-04;
  a14=4.;
  a15=8.9999999999999982e+00;
  a16=3.1415926535897931e+00;
  a17=70.;
  a18=arg[0]? arg[0][5] : 0;
  a18=(a17*a18);
  a19=-20.;
  a18=(a18+a19);
  a20=(a16*a18);
  a21=180.;
  a20=(a20/a21);
  a22=sin(a20);
  a23=casadi_sq(a22);
  a15=(a15-a23);
  a24=sqrt(a15);
  a14=(a14-a24);
  a20=cos(a20);
  a14=(a14-a20);
  a14=(a13*a14);
  a12=(a12+a14);
  a11=(a11/a12);
  a14=1.3999999999999999e+00;
  a14=pow(a11,a14);
  a10=(a10*a14);
  a09=(a09-a10);
  a14=(a06*a09);
  a24=9.9999999999999995e-07;
  a09=casadi_sq(a09);
  a09=(a24+a09);
  a09=sqrt(a09);
  a09=(a06*a09);
  a14=(a14+a09);
  a14=(a14+a10);
  a10=(a14*a12);
  a09=4.7265673220362294e-04;
  a25=3.1998800000000001e-02;
  a26=-1.5475000000000001e+01;
  a27=3.8520879710794719e+02;
  a28=arg[0]? arg[0][1] : 0;
  a28=(a08*a28);
  a29=7.7041759421589438e+02;
  a28=(a28-a29);
  a28=(a28/a29);
  a30=1.;
  a31=(a28+a30);
  a31=casadi_sq(a31);
  a31=(a24+a31);
  a31=sqrt(a31);
  a28=(a28-a30);
  a28=casadi_sq(a28);
  a28=(a24+a28);
  a28=sqrt(a28);
  a31=(a31-a28);
  a27=(a27*a31);
  a27=(a27+a29);
  a29=42600000.;
  a31=(a27/a29);
  a28=1.4856437000000003e-01;
  a31=(a31/a28);
  a26=(a26*a31);
  a25=(a25*a26);
  a26=1.2729341902076080e-04;
  a25=(a25+a26);
  a26=(a09+a25);
  a28=4.4009600000000003e-02;
  a32=1.0800000000000001e+01;
  a32=(a32*a31);
  a28=(a28*a32);
  a32=1.5573144458581126e-05;
  a28=(a28+a32);
  a26=(a26+a28);
  a32=1.8015200000000002e-02;
  a33=9.3499999999999996e+00;
  a33=(a33*a31);
  a32=(a32*a33);
  a33=5.5189420533618726e-06;
  a32=(a32+a33);
  a26=(a26+a32);
  a09=(a09/a26);
  a33=(a07*a09);
  a31=2.5982224333412501e+02;
  a25=(a25/a26);
  a34=(a31*a25);
  a33=(a33+a34);
  a34=1.8891332800116336e+02;
  a28=(a28/a26);
  a35=(a34*a28);
  a33=(a33+a35);
  a35=4.6149917847151289e+02;
  a32=(a32/a26);
  a36=(a35*a32);
  a33=(a33+a36);
  a26=(a26*a33);
  a10=(a10/a26);
  a26=(a08<a10);
  a36=2.9266399999999999e+00;
  a36=(a26?a36:0);
  a37=(!a26);
  a38=3.2986770000000001e+00;
  a38=(a37?a38:0);
  a36=(a36+a38);
  a38=1.4879768000000001e-03;
  a38=(a26?a38:0);
  a39=1.4082404000000000e-03;
  a39=(a37?a39:0);
  a38=(a38+a39);
  a38=(a38*a10);
  a36=(a36+a38);
  a38=-5.6847600000000001e-07;
  a38=(a26?a38:0);
  a39=-3.9632219999999998e-06;
  a39=(a37?a39:0);
  a38=(a38+a39);
  a39=casadi_sq(a10);
  a38=(a38*a39);
  a36=(a36+a38);
  a38=1.0097038000000000e-10;
  a38=(a26?a38:0);
  a40=5.6415150000000002e-09;
  a40=(a37?a40:0);
  a38=(a38+a40);
  a40=(a10*a39);
  a38=(a38*a40);
  a36=(a36+a38);
  a38=-6.7533509999999998e-15;
  a38=(a26?a38:0);
  a41=-2.4448539999999999e-12;
  a41=(a37?a41:0);
  a38=(a38+a41);
  a41=casadi_sq(a39);
  a38=(a38*a41);
  a36=(a36+a38);
  a07=(a07*a36);
  a07=(a07*a09);
  a09=3.2825378399999998e+00;
  a09=(a26?a09:0);
  a36=3.7824563599999999e+00;
  a36=(a37?a36:0);
  a09=(a09+a36);
  a36=1.4830875399999999e-03;
  a36=(a26?a36:0);
  a38=-2.9967341599999998e-03;
  a38=(a37?a38:0);
  a36=(a36+a38);
  a36=(a36*a10);
  a09=(a09+a36);
  a36=-7.5796666899999999e-07;
  a36=(a26?a36:0);
  a38=9.8473020100000000e-06;
  a38=(a37?a38:0);
  a36=(a36+a38);
  a36=(a36*a39);
  a09=(a09+a36);
  a36=2.0947055499999999e-10;
  a36=(a26?a36:0);
  a38=-9.6812950900000007e-09;
  a38=(a37?a38:0);
  a36=(a36+a38);
  a36=(a36*a40);
  a09=(a09+a36);
  a36=-2.1671779399999999e-14;
  a36=(a26?a36:0);
  a38=3.2437283700000000e-12;
  a38=(a37?a38:0);
  a36=(a36+a38);
  a36=(a36*a41);
  a09=(a09+a36);
  a31=(a31*a09);
  a31=(a31*a25);
  a07=(a07+a31);
  a31=3.8574602900000001e+00;
  a31=(a26?a31:0);
  a09=2.3567735200000000e+00;
  a09=(a37?a09:0);
  a31=(a31+a09);
  a09=4.4143702599999998e-03;
  a09=(a26?a09:0);
  a36=8.9845967700000005e-03;
  a36=(a37?a36:0);
  a09=(a09+a36);
  a09=(a09*a10);
  a31=(a31+a09);
  a09=-2.2148140400000001e-06;
  a09=(a26?a09:0);
  a36=-7.1235626899999998e-06;
  a36=(a37?a36:0);
  a09=(a09+a36);
  a09=(a09*a39);
  a31=(a31+a09);
  a09=5.2349018800000005e-10;
  a09=(a26?a09:0);
  a36=2.4591902199999998e-09;
  a36=(a37?a36:0);
  a09=(a09+a36);
  a09=(a09*a40);
  a31=(a31+a09);
  a09=-4.7208416400000003e-14;
  a09=(a26?a09:0);
  a36=-1.4369954799999999e-13;
  a36=(a37?a36:0);
  a09=(a09+a36);
  a09=(a09*a41);
  a31=(a31+a09);
  a34=(a34*a31);
  a34=(a34*a28);
  a07=(a07+a34);
  a34=3.0339924900000002e+00;
  a34=(a26?a34:0);
  a28=4.1986405600000003e+00;
  a28=(a37?a28:0);
  a34=(a34+a28);
  a28=2.1769180400000002e-03;
  a28=(a26?a28:0);
  a31=-2.0364341000000002e-03;
  a31=(a37?a31:0);
  a28=(a28+a31);
  a28=(a28*a10);
  a34=(a34+a28);
  a28=-1.6407251799999999e-07;
  a28=(a26?a28:0);
  a31=6.5204021099999997e-06;
  a31=(a37?a31:0);
  a28=(a28+a31);
  a28=(a28*a39);
  a34=(a34+a28);
  a28=-9.7041986999999998e-11;
  a28=(a26?a28:0);
  a39=-5.4879706200000003e-09;
  a39=(a37?a39:0);
  a28=(a28+a39);
  a28=(a28*a40);
  a34=(a34+a28);
  a28=1.6820099199999999e-14;
  a26=(a26?a28:0);
  a28=1.7719781700000000e-12;
  a37=(a37?a28:0);
  a26=(a26+a37);
  a26=(a26*a41);
  a34=(a34+a26);
  a35=(a35*a34);
  a35=(a35*a32);
  a07=(a07+a35);
  a33=(a07-a33);
  a07=(a07/a33);
  a33=(a07-a30);
  a33=(a33/a12);
  a35=8.3333333333333331e-05;
  a32=8.0000000000000004e-01;
  a34=2.7999999999999998e+00;
  a26=2.1490977393394096e-02;
  a41=pow(a14,a32);
  a26=(a26*a41);
  a41=-5.3000000000000003e-01;
  a41=pow(a10,a41);
  a26=(a26*a41);
  a41=1.9418333333333333e+01;
  a37=5.0000000000000003e-02;
  a28=5.8171812816840792e-06;
  a40=1.3108110000000001e+05;
  a39=1.3300000000000001e+00;
  a11=pow(a11,a39);
  a40=(a40*a11);
  a40=(a14-a40);
  a28=(a28*a40);
  a37=(a37*a28);
  a41=(a41+a37);
  a41=pow(a41,a32);
  a26=(a26*a41);
  a34=(a34*a26);
  a26=1.1334031413612566e-02;
  a41=2.5444024061585990e-01;
  a37=4.7750000000000001e-02;
  a28=3.9999999999999996e+00;
  a28=(a28-a20);
  a40=2.9999999999999996e+00;
  a11=1.1111111111111113e-01;
  a11=(a11*a23);
  a11=(a30-a11);
  a11=sqrt(a11);
  a40=(a40*a11);
  a28=(a28-a40);
  a37=(a37*a28);
  a41=(a41*a37);
  a26=(a26+a41);
  a34=(a34*a26);
  a26=4.7454482412149287e+02;
  a26=(a26-a10);
  a34=(a34*a26);
  a32=(a32*a34);
  a32=(a35*a32);
  a34=2.0876637060343724e-11;
  a26=1000000.;
  a41=12000.;
  a18=(a18/a41);
  a37=5.0000000000000001e-04;
  a28=1.0000000000000000e-03;
  a40=3.1099999999999999e-03;
  a11=4000000.;
  a11=(a14/a11);
  a40=(a40/a11);
  a23=2.2400000000000000e-01;
  a25=(a25/a23);
  a40=(a40/a25);
  a23=4.5100000000000000e-12;
  a39=21079.;
  a39=(a39/a10);
  a39=exp(a39);
  a23=(a23*a39);
  a23=(a40+a23);
  a40=(a40/a23);
  a23=1.2499999999999999e-07;
  a39=-1.0500000000000000e+00;
  a11=pow(a11,a39);
  a23=(a23*a11);
  a11=-1.5000000000000000e+00;
  a25=pow(a25,a11);
  a23=(a23*a25);
  a25=15813.;
  a25=(a25/a10);
  a25=exp(a25);
  a23=(a23*a25);
  a23=(a40*a23);
  a40=(a30-a40);
  a25=1.0900000000000000e-08;
  a11=13188.;
  a11=(a11/a10);
  a11=exp(a11);
  a25=(a25*a11);
  a40=(a40*a25);
  a23=(a23+a40);
  a23=(a28*a23);
  a40=2.5000000000000001e-04;
  a23=(a23+a40);
  a23=(a23-a28);
  a23=(a23/a28);
  a40=(a23+a30);
  a40=casadi_sq(a40);
  a40=(a24+a40);
  a40=sqrt(a40);
  a23=(a23-a30);
  a23=casadi_sq(a23);
  a23=(a24+a23);
  a23=sqrt(a23);
  a40=(a40-a23);
  a37=(a37*a40);
  a37=(a37+a28);
  a18=(a18-a37);
  a18=(a26*a18);
  a01=(a17*a01);
  a01=(a01+a19);
  a01=(a01/a41);
  a01=(a26*a01);
  a40=55.;
  a01=(a01+a40);
  a23=(a18-a01);
  a25=casadi_sq(a23);
  a11=500.;
  a25=(a25+a11);
  a25=sqrt(a25);
  a25=(a25+a23);
  a25=casadi_sq(a25);
  a10=5.5786748793512579e-02;
  a39=2.0930000000000000e+00;
  a31=700.;
  a04=(a31*a04);
  a09=100.;
  a04=(a04+a09);
  a36=6.6730000000000004e+01;
  a04=(a04-a36);
  a38=casadi_sq(a04);
  a38=(a38+a30);
  a38=sqrt(a38);
  a38=(a06*a38);
  a04=(a06*a04);
  a38=(a38+a04);
  a38=(a39*a38);
  a04=(a10*a38);
  a42=5.0103928944824938e-01;
  a04=(a04/a42);
  a43=830.;
  a44=9.0477868423386053e-08;
  a45=4.7592649022342260e+02;
  a46=1.4050000000000000e+00;
  a47=9.3010000000000004e-01;
  a48=2.7439999999999999e-02;
  a49=(a38-a17);
  a50=casadi_sq(a49);
  a50=(a50+a30);
  a50=sqrt(a50);
  a50=(a06*a50);
  a49=(a06*a49);
  a50=(a50+a49);
  a50=(a50+a17);
  a50=(a24*a50);
  a49=-3.6759999999999998e-01;
  a50=pow(a50,a49);
  a50=(a48*a50);
  a50=(a47-a50);
  a50=(a46*a50);
  a51=8.4087818972735737e-03;
  a52=(a50+a51);
  a53=1.0000000000000000e-02;
  a50=(a50-a51);
  a50=casadi_sq(a50);
  a50=(a53+a50);
  a50=sqrt(a50);
  a52=(a52+a50);
  a52=(a06*a52);
  a52=(a45*a52);
  a52=(a44*a52);
  a52=(a43*a52);
  a52=(a08*a52);
  a52=(a52-a04);
  a50=casadi_sq(a52);
  a50=(a50+a53);
  a50=sqrt(a50);
  a50=(a06*a50);
  a04=(a04-a50);
  a52=(a06*a52);
  a04=(a04+a52);
  a52=1.6701309648274978e-01;
  a50=(a04/a52);
  a23=(a23-a50);
  a50=casadi_sq(a23);
  a50=(a50+a11);
  a50=sqrt(a50);
  a50=(a50+a23);
  a50=casadi_sq(a50);
  a25=(a25-a50);
  a25=(a34*a25);
  a50=4.1753274120687449e-11;
  a01=(a01+a38);
  a38=3.3402619296549957e-01;
  a04=(a04/a38);
  a01=(a01-a04);
  a01=(a18-a01);
  a23=casadi_sq(a01);
  a23=(a23+a11);
  a23=sqrt(a23);
  a23=(a23+a01);
  a23=casadi_sq(a23);
  a01=(a01-a04);
  a04=casadi_sq(a01);
  a04=(a04+a11);
  a04=sqrt(a04);
  a04=(a04+a01);
  a04=casadi_sq(a04);
  a23=(a23-a04);
  a23=(a50*a23);
  a25=(a25-a23);
  a03=(a17*a03);
  a03=(a03+a19);
  a03=(a03/a41);
  a03=(a26*a03);
  a03=(a03+a40);
  a40=(a18-a03);
  a41=casadi_sq(a40);
  a41=(a41+a11);
  a41=sqrt(a41);
  a41=(a41+a40);
  a41=casadi_sq(a41);
  a31=(a31*a05);
  a31=(a31+a09);
  a31=(a31-a36);
  a36=casadi_sq(a31);
  a36=(a36+a30);
  a36=sqrt(a36);
  a36=(a06*a36);
  a31=(a06*a31);
  a36=(a36+a31);
  a39=(a39*a36);
  a10=(a10*a39);
  a10=(a10/a42);
  a42=(a39-a17);
  a36=casadi_sq(a42);
  a36=(a36+a30);
  a36=sqrt(a36);
  a36=(a06*a36);
  a42=(a06*a42);
  a36=(a36+a42);
  a36=(a36+a17);
  a24=(a24*a36);
  a24=pow(a24,a49);
  a48=(a48*a24);
  a47=(a47-a48);
  a46=(a46*a47);
  a47=(a46+a51);
  a46=(a46-a51);
  a46=casadi_sq(a46);
  a46=(a53+a46);
  a46=sqrt(a46);
  a47=(a47+a46);
  a47=(a06*a47);
  a45=(a45*a47);
  a44=(a44*a45);
  a43=(a43*a44);
  a08=(a08*a43);
  a08=(a08-a10);
  a43=casadi_sq(a08);
  a43=(a43+a53);
  a43=sqrt(a43);
  a43=(a06*a43);
  a10=(a10-a43);
  a08=(a06*a08);
  a10=(a10+a08);
  a52=(a10/a52);
  a40=(a40-a52);
  a52=casadi_sq(a40);
  a52=(a52+a11);
  a52=sqrt(a52);
  a52=(a52+a40);
  a52=casadi_sq(a52);
  a41=(a41-a52);
  a34=(a34*a41);
  a03=(a03+a39);
  a10=(a10/a38);
  a03=(a03-a10);
  a18=(a18-a03);
  a03=casadi_sq(a18);
  a03=(a03+a11);
  a03=sqrt(a03);
  a03=(a03+a18);
  a03=casadi_sq(a03);
  a18=(a18-a10);
  a10=casadi_sq(a18);
  a10=(a10+a11);
  a10=sqrt(a10);
  a10=(a10+a18);
  a10=casadi_sq(a10);
  a03=(a03-a10);
  a50=(a50*a03);
  a34=(a34-a50);
  a25=(a25+a34);
  a29=(a29*a25);
  a29=(a29-a27);
  a35=(a35*a29);
  a27=3800.;
  a25=-2.0000000000000003e+05;
  a34=2.7999999999999998e-04;
  a37=(a37-a34);
  a25=(a25*a37);
  a25=exp(a25);
  a25=(a30+a25);
  a27=(a27/a25);
  a37=2070.;
  a25=(1./a25);
  a25=(a30-a25);
  a37=(a37*a25);
  a27=(a27+a37);
  a35=(a35*a27);
  a27=5.2700000000000002e-04;
  a27=(a27*a25);
  a29=(a29*a27);
  a30=(a30-a29);
  a35=(a35/a30);
  a30=(a06*a35);
  a29=1.0000000000000000e-08;
  a35=casadi_sq(a35);
  a29=(a29+a35);
  a29=sqrt(a29);
  a29=(a06*a29);
  a30=(a30+a29);
  a32=(a32+a30);
  a33=(a33*a32);
  a07=(a07*a14);
  a14=-5.0000000000000000e-01;
  a15=pow(a15,a14);
  a15=(a15*a22);
  a15=(a15*a20);
  a22=(a22+a15);
  a13=(a13*a22);
  a16=(a16*a13);
  a16=(a16/a21);
  a07=(a07*a16);
  a07=(a07/a12);
  a33=(a33-a07);
  a33=(a33-a26);
  a26=100000.;
  a33=(a33/a26);
  a26=casadi_sq(a33);
  a26=(a26+a28);
  a26=sqrt(a26);
  a33=(a33+a26);
  a06=(a06*a33);
  a06=casadi_sq(a06);
  a02=(a02*a06);
  a00=(a00+a02);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
