/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* ECO_opt_2inj_cost_ext_cost_e_fun:(i0[10],i1[0],i2[0],i3)->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25;
  a00=42600000.;
  a01=1.0000000000000001e-09;
  a02=2.0930000000000000e+00;
  a03=5.0000000000000000e-01;
  a04=700.;
  a05=arg[0]? arg[0][2] : 0;
  a05=(a04*a05);
  a06=100.;
  a05=(a05+a06);
  a07=6.6730000000000004e+01;
  a05=(a05-a07);
  a08=casadi_sq(a05);
  a09=1.;
  a08=(a08+a09);
  a08=sqrt(a08);
  a08=(a03*a08);
  a05=(a03*a05);
  a08=(a08+a05);
  a08=(a02*a08);
  a05=5.5786748793512579e-02;
  a10=(a05*a08);
  a11=5.0103928944824938e-01;
  a10=(a10/a11);
  a12=1000.;
  a13=830.;
  a14=9.0477868423386053e-08;
  a15=4.7592649022342260e+02;
  a16=1.4050000000000000e+00;
  a17=9.3010000000000004e-01;
  a18=2.7439999999999999e-02;
  a19=9.9999999999999995e-07;
  a20=70.;
  a21=(a08-a20);
  a22=casadi_sq(a21);
  a22=(a22+a09);
  a22=sqrt(a22);
  a22=(a03*a22);
  a21=(a03*a21);
  a22=(a22+a21);
  a22=(a22+a20);
  a22=(a19*a22);
  a21=-3.6759999999999998e-01;
  a22=pow(a22,a21);
  a22=(a18*a22);
  a22=(a17-a22);
  a22=(a16*a22);
  a23=8.4087818972735737e-03;
  a24=(a22+a23);
  a25=1.0000000000000000e-02;
  a22=(a22-a23);
  a22=casadi_sq(a22);
  a22=(a25+a22);
  a22=sqrt(a22);
  a24=(a24+a22);
  a24=(a03*a24);
  a24=(a15*a24);
  a24=(a14*a24);
  a24=(a13*a24);
  a24=(a12*a24);
  a24=(a24-a10);
  a22=casadi_sq(a24);
  a22=(a22+a25);
  a22=sqrt(a22);
  a22=(a03*a22);
  a10=(a10-a22);
  a24=(a03*a24);
  a10=(a10+a24);
  a08=(a08*a10);
  a24=8.9813315936869049e+00;
  a10=casadi_sq(a10);
  a10=(a03*a10);
  a10=(a24*a10);
  a08=(a08-a10);
  a08=(a01*a08);
  a10=arg[0]? arg[0][3] : 0;
  a04=(a04*a10);
  a04=(a04+a06);
  a04=(a04-a07);
  a07=casadi_sq(a04);
  a07=(a07+a09);
  a07=sqrt(a07);
  a07=(a03*a07);
  a04=(a03*a04);
  a07=(a07+a04);
  a02=(a02*a07);
  a05=(a05*a02);
  a05=(a05/a11);
  a11=(a02-a20);
  a07=casadi_sq(a11);
  a07=(a07+a09);
  a07=sqrt(a07);
  a07=(a03*a07);
  a11=(a03*a11);
  a07=(a07+a11);
  a07=(a07+a20);
  a19=(a19*a07);
  a19=pow(a19,a21);
  a18=(a18*a19);
  a17=(a17-a18);
  a16=(a16*a17);
  a17=(a16+a23);
  a16=(a16-a23);
  a16=casadi_sq(a16);
  a16=(a25+a16);
  a16=sqrt(a16);
  a17=(a17+a16);
  a17=(a03*a17);
  a15=(a15*a17);
  a14=(a14*a15);
  a13=(a13*a14);
  a13=(a12*a13);
  a13=(a13-a05);
  a14=casadi_sq(a13);
  a14=(a14+a25);
  a14=sqrt(a14);
  a14=(a03*a14);
  a05=(a05-a14);
  a13=(a03*a13);
  a05=(a05+a13);
  a02=(a02*a05);
  a05=casadi_sq(a05);
  a03=(a03*a05);
  a24=(a24*a03);
  a02=(a02-a24);
  a01=(a01*a02);
  a08=(a08+a01);
  a00=(a00*a08);
  a00=(a00/a12);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
