/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* ECO_opt_2inj_cost_ext_cost_e_fun_jac:(i0[10],i1[0],i2[0],i3)->(o0,o1[10]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=42600000.;
  a01=1.0000000000000001e-09;
  a02=2.0930000000000000e+00;
  a03=5.0000000000000000e-01;
  a04=700.;
  a05=arg[0]? arg[0][2] : 0;
  a05=(a04*a05);
  a06=100.;
  a05=(a05+a06);
  a07=6.6730000000000004e+01;
  a05=(a05-a07);
  a08=casadi_sq(a05);
  a09=1.;
  a08=(a08+a09);
  a08=sqrt(a08);
  a10=(a03*a08);
  a11=(a03*a05);
  a10=(a10+a11);
  a10=(a02*a10);
  a11=5.5786748793512579e-02;
  a12=(a11*a10);
  a13=5.0103928944824938e-01;
  a12=(a12/a13);
  a14=1000.;
  a15=830.;
  a16=9.0477868423386053e-08;
  a17=4.7592649022342260e+02;
  a18=1.4050000000000000e+00;
  a19=9.3010000000000004e-01;
  a20=2.7439999999999999e-02;
  a21=9.9999999999999995e-07;
  a22=70.;
  a23=(a10-a22);
  a24=casadi_sq(a23);
  a24=(a24+a09);
  a24=sqrt(a24);
  a25=(a03*a24);
  a26=(a03*a23);
  a25=(a25+a26);
  a25=(a25+a22);
  a25=(a21*a25);
  a26=-3.6759999999999998e-01;
  a27=pow(a25,a26);
  a27=(a20*a27);
  a27=(a19-a27);
  a27=(a18*a27);
  a28=8.4087818972735737e-03;
  a29=(a27+a28);
  a30=1.0000000000000000e-02;
  a27=(a27-a28);
  a31=casadi_sq(a27);
  a31=(a30+a31);
  a31=sqrt(a31);
  a29=(a29+a31);
  a29=(a03*a29);
  a29=(a17*a29);
  a29=(a16*a29);
  a29=(a15*a29);
  a29=(a14*a29);
  a29=(a29-a12);
  a32=casadi_sq(a29);
  a32=(a32+a30);
  a32=sqrt(a32);
  a33=(a03*a32);
  a12=(a12-a33);
  a33=(a03*a29);
  a12=(a12+a33);
  a33=(a10*a12);
  a34=8.9813315936869049e+00;
  a35=casadi_sq(a12);
  a35=(a03*a35);
  a35=(a34*a35);
  a33=(a33-a35);
  a33=(a01*a33);
  a35=arg[0]? arg[0][3] : 0;
  a35=(a04*a35);
  a35=(a35+a06);
  a35=(a35-a07);
  a07=casadi_sq(a35);
  a07=(a07+a09);
  a07=sqrt(a07);
  a06=(a03*a07);
  a36=(a03*a35);
  a06=(a06+a36);
  a06=(a02*a06);
  a36=(a11*a06);
  a36=(a36/a13);
  a13=(a06-a22);
  a37=casadi_sq(a13);
  a37=(a37+a09);
  a37=sqrt(a37);
  a09=(a03*a37);
  a38=(a03*a13);
  a09=(a09+a38);
  a09=(a09+a22);
  a09=(a21*a09);
  a22=pow(a09,a26);
  a22=(a20*a22);
  a19=(a19-a22);
  a19=(a18*a19);
  a22=(a19+a28);
  a19=(a19-a28);
  a28=casadi_sq(a19);
  a28=(a30+a28);
  a28=sqrt(a28);
  a22=(a22+a28);
  a22=(a03*a22);
  a22=(a17*a22);
  a22=(a16*a22);
  a22=(a15*a22);
  a22=(a14*a22);
  a22=(a22-a36);
  a38=casadi_sq(a22);
  a38=(a38+a30);
  a38=sqrt(a38);
  a30=(a03*a38);
  a36=(a36-a30);
  a30=(a03*a22);
  a36=(a36+a30);
  a30=(a06*a36);
  a39=casadi_sq(a36);
  a39=(a03*a39);
  a34=(a34*a39);
  a30=(a30-a34);
  a01=(a01*a30);
  a33=(a33+a01);
  a00=(a00*a33);
  a00=(a00/a14);
  if (res[0]!=0) res[0][0]=a00;
  a00=0.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  a33=4.2600000000000005e-05;
  a01=(a33*a12);
  a30=-1.3675999999999999e+00;
  a25=pow(a25,a30);
  a25=(a26*a25);
  a27=(a27+a27);
  a34=-1.9130236294553110e-04;
  a12=(a12+a12);
  a12=(a34*a12);
  a10=(a33*a10);
  a12=(a12+a10);
  a10=(a03*a12);
  a29=(a29+a29);
  a32=(a32+a32);
  a32=(a10/a32);
  a29=(a29*a32);
  a32=(a10-a29);
  a32=(a14*a32);
  a32=(a15*a32);
  a32=(a16*a32);
  a32=(a17*a32);
  a32=(a03*a32);
  a31=(a31+a31);
  a31=(a32/a31);
  a27=(a27*a31);
  a27=(a27+a32);
  a27=(a18*a27);
  a27=(a20*a27);
  a25=(a25*a27);
  a25=(a21*a25);
  a25=(a03*a25);
  a01=(a01-a25);
  a23=(a23+a23);
  a24=(a24+a24);
  a25=(a25/a24);
  a23=(a23*a25);
  a01=(a01-a23);
  a23=1.9958514652637567e+00;
  a12=(a12-a10);
  a12=(a12+a29);
  a12=(a23*a12);
  a12=(a11*a12);
  a01=(a01+a12);
  a01=(a02*a01);
  a01=(a03*a01);
  a05=(a05+a05);
  a08=(a08+a08);
  a08=(a01/a08);
  a05=(a05*a08);
  a01=(a01+a05);
  a01=(a04*a01);
  if (res[1]!=0) res[1][2]=a01;
  a01=(a33*a36);
  a09=pow(a09,a30);
  a26=(a26*a09);
  a19=(a19+a19);
  a36=(a36+a36);
  a34=(a34*a36);
  a33=(a33*a06);
  a34=(a34+a33);
  a33=(a03*a34);
  a22=(a22+a22);
  a38=(a38+a38);
  a38=(a33/a38);
  a22=(a22*a38);
  a38=(a33-a22);
  a14=(a14*a38);
  a15=(a15*a14);
  a16=(a16*a15);
  a17=(a17*a16);
  a17=(a03*a17);
  a28=(a28+a28);
  a28=(a17/a28);
  a19=(a19*a28);
  a19=(a19+a17);
  a18=(a18*a19);
  a20=(a20*a18);
  a26=(a26*a20);
  a21=(a21*a26);
  a21=(a03*a21);
  a01=(a01-a21);
  a13=(a13+a13);
  a37=(a37+a37);
  a21=(a21/a37);
  a13=(a13*a21);
  a01=(a01-a13);
  a34=(a34-a33);
  a34=(a34+a22);
  a23=(a23*a34);
  a11=(a11*a23);
  a01=(a01+a11);
  a02=(a02*a01);
  a03=(a03*a02);
  a35=(a35+a35);
  a07=(a07+a07);
  a07=(a03/a07);
  a35=(a35*a07);
  a03=(a03+a35);
  a04=(a04*a03);
  if (res[1]!=0) res[1][3]=a04;
  if (res[1]!=0) res[1][4]=a00;
  if (res[1]!=0) res[1][5]=a00;
  if (res[1]!=0) res[1][6]=a00;
  if (res[1]!=0) res[1][7]=a00;
  if (res[1]!=0) res[1][8]=a00;
  if (res[1]!=0) res[1][9]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
