"""Locate the acados installation and load its shared libraries.

ECO needs to know where acados is installed. That location is configured in
exactly one place — ``ACADOS_SOURCE_DIR`` in ``python_code/.env``::

    ACADOS_SOURCE_DIR=/path/to/acados

It can equally be exported as a shell environment variable, which takes
precedence over the file. Everything else (the ``lib/`` directory,
``LD_LIBRARY_PATH``) is derived from it. If neither is set, a few conventional
locations are tried before giving up with an actionable error.

Call :func:`load_acados` once, before importing ``acados_template`` or building
a solver.
"""

import ctypes
import os
import sys
import warnings
from pathlib import Path
from typing import Dict, List

#: Loaded with ``RTLD_GLOBAL`` so the generated solver resolves their symbols.
_SHARED_LIBS = ('libblasfeo', 'libhpipm', 'libqpOASES_e', 'libacados')

#: ``python_code/`` — the directory containing the ``eco`` package.
PACKAGE_ROOT = Path(__file__).resolve().parents[1]


def _read_dotenv(path: Path) -> Dict[str, str]:
    """Parse a simple ``KEY=VALUE`` .env file; return {} if it does not exist."""
    values: Dict[str, str] = {}
    if not path.is_file():
        return values
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        values[key.strip()] = os.path.expandvars(value.strip().strip('"\''))
    return values


def find_acados() -> Path:
    """Return the root directory of the acados installation.

    Searched in order: ``ACADOS_SOURCE_DIR`` in the environment, then in
    ``python_code/.env``, then ``../acados`` next to this repository, then
    ``~/acados``.

    Raises:
        RuntimeError: if no directory containing ``lib/`` is found.
    """
    candidates: List[Path] = []

    from_env = os.environ.get('ACADOS_SOURCE_DIR')
    if from_env:
        candidates.append(Path(from_env).expanduser())

    from_dotenv = _read_dotenv(PACKAGE_ROOT / '.env').get('ACADOS_SOURCE_DIR')
    if from_dotenv:
        candidates.append(Path(from_dotenv).expanduser())

    candidates.append(PACKAGE_ROOT.parent / 'acados')   # sibling checkout
    candidates.append(Path.home() / 'acados')

    for candidate in candidates:
        if (candidate / 'lib').is_dir():
            return candidate.resolve()

    searched = '\n'.join(f'  - {c}' for c in candidates)
    raise RuntimeError(
        'Could not locate the acados installation.\n'
        'Set ACADOS_SOURCE_DIR to the root of your acados build, e.g.\n'
        '    export ACADOS_SOURCE_DIR=/path/to/acados\n'
        f'or put the same line in {PACKAGE_ROOT / ".env"}.\n'
        f'Looked in:\n{searched}'
    )


def check_acados_template(acados_dir: Path) -> None:
    """Verify the acados Python interface is installed from ``acados_dir``.

    ``acados_template`` generates and compiles C code against the acados library
    and must therefore come from the same tree, not from PyPI.

    Args:
        acados_dir: The acados root directory, as returned by :func:`find_acados`.

    Raises:
        RuntimeError: if ``acados_template`` is not installed at all.
    """
    interface_dir = (acados_dir / 'interfaces' / 'acados_template').resolve()

    try:
        import acados_template
    except ImportError:
        raise RuntimeError(
            'The acados Python interface (acados_template) is not installed.\n'
            'Install it from the acados tree configured in .env, so that it '
            'matches the compiled C library:\n'
            f'    pip install -e {interface_dir}\n'
            'See https://docs.acados.org/python_interface/index.html'
        ) from None

    installed_from = Path(acados_template.__file__).resolve().parents[1]
    if installed_from != interface_dir:
        warnings.warn(
            f'acados_template is imported from {installed_from}, but '
            f'ACADOS_SOURCE_DIR points at {acados_dir}. The Python interface '
            'and the compiled C library may not match. Reinstall with:\n'
            f'    pip install -e {interface_dir}',
            RuntimeWarning, stacklevel=2)


def load_acados(verbose: bool = False) -> Path:
    """Load the acados shared libraries into the current process.

    Sets ``ACADOS_SOURCE_DIR`` and prepends the acados ``lib/`` directory to
    ``LD_LIBRARY_PATH`` so the C code generated by ``acados_template`` compiles
    and links against the same installation, then checks that the Python
    interface comes from that same tree.

    Args:
        verbose: Print the resolved installation directory.

    Returns:
        The acados root directory.

    Raises:
        RuntimeError: if acados or its Python interface cannot be found.
    """
    acados_dir = find_acados()
    lib_dir = acados_dir / 'lib'

    os.environ['ACADOS_SOURCE_DIR'] = str(acados_dir)
    os.environ['LD_LIBRARY_PATH'] = os.pathsep.join(
        p for p in (str(lib_dir), os.environ.get('LD_LIBRARY_PATH', '')) if p)

    suffix = '.dylib' if sys.platform == 'darwin' else '.so'
    for name in _SHARED_LIBS:
        lib_path = lib_dir / f'{name}{suffix}'
        if lib_path.is_file():
            ctypes.CDLL(str(lib_path), mode=ctypes.RTLD_GLOBAL)

    check_acados_template(acados_dir)

    if verbose:
        print(f'  acados: {acados_dir}')

    return acados_dir
