/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};

/* ECO_opt_2inj_constr_h_e_fun:(i0[10],i1[0],i2[0],i3)->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27;
  a00=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=5.0000000000000000e-01;
  a01=10000000.;
  a02=arg[0]? arg[0][4] : 0;
  a01=(a01*a02);
  a02=1.0486488000000000e+05;
  a03=5.2214244335811971e-04;
  a04=3.1741935483870970e-05;
  a05=2.4600000000000002e-04;
  a06=4.;
  a07=8.9999999999999982e+00;
  a08=3.1415926535897931e+00;
  a09=70.;
  a10=arg[0]? arg[0][9] : 0;
  a10=(a09*a10);
  a11=-20.;
  a10=(a10+a11);
  a08=(a08*a10);
  a10=180.;
  a08=(a08/a10);
  a10=sin(a08);
  a10=casadi_sq(a10);
  a07=(a07-a10);
  a07=sqrt(a07);
  a06=(a06-a07);
  a08=cos(a08);
  a06=(a06-a08);
  a05=(a05*a06);
  a04=(a04+a05);
  a03=(a03/a04);
  a05=1.3999999999999999e+00;
  a03=pow(a03,a05);
  a02=(a02*a03);
  a01=(a01-a02);
  a03=(a00*a01);
  a05=9.9999999999999995e-07;
  a01=casadi_sq(a01);
  a01=(a05+a01);
  a01=sqrt(a01);
  a01=(a00*a01);
  a03=(a03+a01);
  a03=(a03+a02);
  a02=(a03*a04);
  a01=4.7265673220362294e-04;
  a06=3.1998800000000001e-02;
  a08=-1.5475000000000001e+01;
  a07=3.8520879710794719e+02;
  a10=1000.;
  a11=arg[0]? arg[0][5] : 0;
  a11=(a10*a11);
  a12=7.7041759421589438e+02;
  a11=(a11-a12);
  a11=(a11/a12);
  a13=1.;
  a14=(a11+a13);
  a14=casadi_sq(a14);
  a14=(a05+a14);
  a14=sqrt(a14);
  a11=(a11-a13);
  a11=casadi_sq(a11);
  a11=(a05+a11);
  a11=sqrt(a11);
  a14=(a14-a11);
  a07=(a07*a14);
  a07=(a07+a12);
  a12=42600000.;
  a07=(a07/a12);
  a12=1.4856437000000003e-01;
  a12=(a07/a12);
  a08=(a08*a12);
  a06=(a06*a08);
  a08=1.2729341902076080e-04;
  a06=(a06+a08);
  a08=(a01+a06);
  a14=4.4009600000000003e-02;
  a11=1.0800000000000001e+01;
  a11=(a11*a12);
  a14=(a14*a11);
  a11=1.5573144458581126e-05;
  a14=(a14+a11);
  a08=(a08+a14);
  a11=1.8015200000000002e-02;
  a15=9.3499999999999996e+00;
  a15=(a15*a12);
  a11=(a11*a15);
  a15=5.5189420533618726e-06;
  a11=(a11+a15);
  a08=(a08+a11);
  a15=2.9678653787116167e+02;
  a01=(a01/a08);
  a15=(a15*a01);
  a01=2.5982224333412501e+02;
  a06=(a06/a08);
  a01=(a01*a06);
  a15=(a15+a01);
  a01=1.8891332800116336e+02;
  a14=(a14/a08);
  a01=(a01*a14);
  a15=(a15+a01);
  a01=4.6149917847151289e+02;
  a11=(a11/a08);
  a01=(a01*a11);
  a15=(a15+a01);
  a08=(a08*a15);
  a08=(a02/a08);
  a15=(a08/a10);
  if (res[0]!=0) res[0][1]=a15;
  a15=1000000.;
  a01=arg[0]? arg[0][8] : 0;
  a01=(a05*a01);
  a11=(a00*a01);
  a14=1.0000000000000001e-20;
  a01=casadi_sq(a01);
  a14=(a14+a01);
  a14=sqrt(a14);
  a14=(a00*a14);
  a11=(a11+a14);
  a11=(a15*a11);
  a14=2.8796878496782119e+02;
  a01=6.2104223773632675e-04;
  a06=1.1363636363636365e+00;
  a12=1.4310260600938740e+01;
  a07=(a12*a07);
  a06=(a06*a07);
  a06=(a01-a06);
  a14=(a14*a06);
  a06=arg[0]? arg[0][7] : 0;
  a06=(a10*a06);
  a14=(a14*a06);
  a14=(a14/a03);
  a04=(a04-a14);
  a15=(a15*a04);
  a11=(a11*a15);
  a15=8.3140000000000001e+00;
  a15=(a15*a08);
  a02=(a02/a15);
  a11=(a11/a02);
  a11=(a11/a10);
  if (res[0]!=0) res[0][2]=a11;
  a11=2.3291751145757966e-01;
  a02=1.0000000000000001e-09;
  a15=2.0930000000000000e+00;
  a08=700.;
  a04=arg[0]? arg[0][2] : 0;
  a04=(a08*a04);
  a14=100.;
  a04=(a04+a14);
  a03=6.6730000000000004e+01;
  a04=(a04-a03);
  a06=casadi_sq(a04);
  a06=(a06+a13);
  a06=sqrt(a06);
  a06=(a00*a06);
  a04=(a00*a04);
  a06=(a06+a04);
  a06=(a15*a06);
  a04=5.5786748793512579e-02;
  a07=(a04*a06);
  a16=5.0103928944824938e-01;
  a07=(a07/a16);
  a17=830.;
  a18=9.0477868423386053e-08;
  a19=4.7592649022342260e+02;
  a20=1.4050000000000000e+00;
  a21=9.3010000000000004e-01;
  a22=2.7439999999999999e-02;
  a23=(a06-a09);
  a24=casadi_sq(a23);
  a24=(a24+a13);
  a24=sqrt(a24);
  a24=(a00*a24);
  a23=(a00*a23);
  a24=(a24+a23);
  a24=(a24+a09);
  a24=(a05*a24);
  a23=-3.6759999999999998e-01;
  a24=pow(a24,a23);
  a24=(a22*a24);
  a24=(a21-a24);
  a24=(a20*a24);
  a25=8.4087818972735737e-03;
  a26=(a24+a25);
  a27=1.0000000000000000e-02;
  a24=(a24-a25);
  a24=casadi_sq(a24);
  a24=(a27+a24);
  a24=sqrt(a24);
  a26=(a26+a24);
  a26=(a00*a26);
  a26=(a19*a26);
  a26=(a18*a26);
  a26=(a17*a26);
  a26=(a10*a26);
  a26=(a26-a07);
  a24=casadi_sq(a26);
  a24=(a24+a27);
  a24=sqrt(a24);
  a24=(a00*a24);
  a07=(a07-a24);
  a26=(a00*a26);
  a07=(a07+a26);
  a26=(a06*a07);
  a24=8.9813315936869049e+00;
  a07=casadi_sq(a07);
  a07=(a00*a07);
  a07=(a24*a07);
  a26=(a26-a07);
  a26=(a02*a26);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a08*a07);
  a08=(a08+a14);
  a08=(a08-a03);
  a03=casadi_sq(a08);
  a03=(a03+a13);
  a03=sqrt(a03);
  a03=(a00*a03);
  a08=(a00*a08);
  a03=(a03+a08);
  a15=(a15*a03);
  a04=(a04*a15);
  a04=(a04/a16);
  a16=(a15-a09);
  a03=casadi_sq(a16);
  a03=(a03+a13);
  a03=sqrt(a03);
  a03=(a00*a03);
  a16=(a00*a16);
  a03=(a03+a16);
  a03=(a03+a09);
  a03=(a05*a03);
  a03=pow(a03,a23);
  a22=(a22*a03);
  a21=(a21-a22);
  a20=(a20*a21);
  a21=(a20+a25);
  a20=(a20-a25);
  a20=casadi_sq(a20);
  a20=(a27+a20);
  a20=sqrt(a20);
  a21=(a21+a20);
  a21=(a00*a21);
  a19=(a19*a21);
  a18=(a18*a19);
  a17=(a17*a18);
  a10=(a10*a17);
  a10=(a10-a04);
  a17=casadi_sq(a10);
  a17=(a17+a27);
  a17=sqrt(a17);
  a17=(a00*a17);
  a04=(a04-a17);
  a10=(a00*a10);
  a04=(a04+a10);
  a15=(a15*a04);
  a04=casadi_sq(a04);
  a00=(a00*a04);
  a24=(a24*a00);
  a15=(a15-a24);
  a02=(a02*a15);
  a26=(a26+a02);
  a12=(a12*a26);
  a11=(a11*a12);
  a11=(a11/a01);
  a01=2.0496741008267014e-01;
  a11=(a11/a01);
  if (res[0]!=0) res[0][3]=a11;
  a11=arg[0]? arg[0][1] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a11=(a11-a01);
  a01=360.;
  a12=3.3333333333333336e+01;
  a26=arg[3]? arg[3][0] : 0;
  a06=(a06+a26);
  a12=(a12*a06);
  a01=(a01*a12);
  a05=(a05*a01);
  a05=(a05/a09);
  a11=(a11-a05);
  if (res[0]!=0) res[0][4]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_constr_h_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
