/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};

/* ECO_opt_2inj_constr_h_fun:(i0[10],i1[0],i2[0],i3)->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=2.9678653787116167e+02;
  a02=1000.;
  a03=5.0000000000000000e-01;
  a04=10000000.;
  a00=(a04*a00);
  a05=1.0486488000000000e+05;
  a06=5.2214244335811971e-04;
  a07=3.1741935483870970e-05;
  a08=2.4600000000000002e-04;
  a09=4.;
  a10=8.9999999999999982e+00;
  a11=3.1415926535897931e+00;
  a12=70.;
  a13=arg[0]? arg[0][9] : 0;
  a13=(a12*a13);
  a14=-20.;
  a13=(a13+a14);
  a15=(a11*a13);
  a16=180.;
  a15=(a15/a16);
  a17=sin(a15);
  a18=casadi_sq(a17);
  a10=(a10-a18);
  a19=sqrt(a10);
  a09=(a09-a19);
  a15=cos(a15);
  a09=(a09-a15);
  a09=(a08*a09);
  a07=(a07+a09);
  a06=(a06/a07);
  a09=1.3999999999999999e+00;
  a09=pow(a06,a09);
  a05=(a05*a09);
  a00=(a00-a05);
  a09=(a03*a00);
  a19=9.9999999999999995e-07;
  a00=casadi_sq(a00);
  a00=(a19+a00);
  a00=sqrt(a00);
  a00=(a03*a00);
  a09=(a09+a00);
  a09=(a09+a05);
  a05=(a09*a07);
  a00=4.7265673220362294e-04;
  a20=3.1998800000000001e-02;
  a21=-1.5475000000000001e+01;
  a22=3.8520879710794719e+02;
  a23=arg[0]? arg[0][5] : 0;
  a24=(a02*a23);
  a25=7.7041759421589438e+02;
  a24=(a24-a25);
  a24=(a24/a25);
  a26=1.;
  a27=(a24+a26);
  a27=casadi_sq(a27);
  a27=(a19+a27);
  a27=sqrt(a27);
  a24=(a24-a26);
  a24=casadi_sq(a24);
  a24=(a19+a24);
  a24=sqrt(a24);
  a27=(a27-a24);
  a22=(a22*a27);
  a22=(a22+a25);
  a25=42600000.;
  a27=(a22/a25);
  a24=1.4856437000000003e-01;
  a27=(a27/a24);
  a21=(a21*a27);
  a20=(a20*a21);
  a21=1.2729341902076080e-04;
  a20=(a20+a21);
  a21=(a00+a20);
  a24=4.4009600000000003e-02;
  a28=1.0800000000000001e+01;
  a28=(a28*a27);
  a24=(a24*a28);
  a28=1.5573144458581126e-05;
  a24=(a24+a28);
  a21=(a21+a24);
  a28=1.8015200000000002e-02;
  a29=9.3499999999999996e+00;
  a29=(a29*a27);
  a28=(a28*a29);
  a29=5.5189420533618726e-06;
  a28=(a28+a29);
  a21=(a21+a28);
  a00=(a00/a21);
  a29=(a01*a00);
  a27=2.5982224333412501e+02;
  a20=(a20/a21);
  a30=(a27*a20);
  a29=(a29+a30);
  a30=1.8891332800116336e+02;
  a24=(a24/a21);
  a31=(a30*a24);
  a29=(a29+a31);
  a31=4.6149917847151289e+02;
  a28=(a28/a21);
  a32=(a31*a28);
  a29=(a29+a32);
  a21=(a21*a29);
  a05=(a05/a21);
  a21=(a02<a05);
  a32=2.9266399999999999e+00;
  a32=(a21?a32:0);
  a33=(!a21);
  a34=3.2986770000000001e+00;
  a34=(a33?a34:0);
  a32=(a32+a34);
  a34=1.4879768000000001e-03;
  a34=(a21?a34:0);
  a35=1.4082404000000000e-03;
  a35=(a33?a35:0);
  a34=(a34+a35);
  a34=(a34*a05);
  a32=(a32+a34);
  a34=-5.6847600000000001e-07;
  a34=(a21?a34:0);
  a35=-3.9632219999999998e-06;
  a35=(a33?a35:0);
  a34=(a34+a35);
  a35=casadi_sq(a05);
  a34=(a34*a35);
  a32=(a32+a34);
  a34=1.0097038000000000e-10;
  a34=(a21?a34:0);
  a36=5.6415150000000002e-09;
  a36=(a33?a36:0);
  a34=(a34+a36);
  a36=(a05*a35);
  a34=(a34*a36);
  a32=(a32+a34);
  a34=-6.7533509999999998e-15;
  a34=(a21?a34:0);
  a37=-2.4448539999999999e-12;
  a37=(a33?a37:0);
  a34=(a34+a37);
  a37=casadi_sq(a35);
  a34=(a34*a37);
  a32=(a32+a34);
  a01=(a01*a32);
  a01=(a01*a00);
  a00=3.2825378399999998e+00;
  a00=(a21?a00:0);
  a32=3.7824563599999999e+00;
  a32=(a33?a32:0);
  a00=(a00+a32);
  a32=1.4830875399999999e-03;
  a32=(a21?a32:0);
  a34=-2.9967341599999998e-03;
  a34=(a33?a34:0);
  a32=(a32+a34);
  a32=(a32*a05);
  a00=(a00+a32);
  a32=-7.5796666899999999e-07;
  a32=(a21?a32:0);
  a34=9.8473020100000000e-06;
  a34=(a33?a34:0);
  a32=(a32+a34);
  a32=(a32*a35);
  a00=(a00+a32);
  a32=2.0947055499999999e-10;
  a32=(a21?a32:0);
  a34=-9.6812950900000007e-09;
  a34=(a33?a34:0);
  a32=(a32+a34);
  a32=(a32*a36);
  a00=(a00+a32);
  a32=-2.1671779399999999e-14;
  a32=(a21?a32:0);
  a34=3.2437283700000000e-12;
  a34=(a33?a34:0);
  a32=(a32+a34);
  a32=(a32*a37);
  a00=(a00+a32);
  a27=(a27*a00);
  a27=(a27*a20);
  a01=(a01+a27);
  a27=3.8574602900000001e+00;
  a27=(a21?a27:0);
  a00=2.3567735200000000e+00;
  a00=(a33?a00:0);
  a27=(a27+a00);
  a00=4.4143702599999998e-03;
  a00=(a21?a00:0);
  a32=8.9845967700000005e-03;
  a32=(a33?a32:0);
  a00=(a00+a32);
  a00=(a00*a05);
  a27=(a27+a00);
  a00=-2.2148140400000001e-06;
  a00=(a21?a00:0);
  a32=-7.1235626899999998e-06;
  a32=(a33?a32:0);
  a00=(a00+a32);
  a00=(a00*a35);
  a27=(a27+a00);
  a00=5.2349018800000005e-10;
  a00=(a21?a00:0);
  a32=2.4591902199999998e-09;
  a32=(a33?a32:0);
  a00=(a00+a32);
  a00=(a00*a36);
  a27=(a27+a00);
  a00=-4.7208416400000003e-14;
  a00=(a21?a00:0);
  a32=-1.4369954799999999e-13;
  a32=(a33?a32:0);
  a00=(a00+a32);
  a00=(a00*a37);
  a27=(a27+a00);
  a30=(a30*a27);
  a30=(a30*a24);
  a01=(a01+a30);
  a30=3.0339924900000002e+00;
  a30=(a21?a30:0);
  a24=4.1986405600000003e+00;
  a24=(a33?a24:0);
  a30=(a30+a24);
  a24=2.1769180400000002e-03;
  a24=(a21?a24:0);
  a27=-2.0364341000000002e-03;
  a27=(a33?a27:0);
  a24=(a24+a27);
  a24=(a24*a05);
  a30=(a30+a24);
  a24=-1.6407251799999999e-07;
  a24=(a21?a24:0);
  a27=6.5204021099999997e-06;
  a27=(a33?a27:0);
  a24=(a24+a27);
  a24=(a24*a35);
  a30=(a30+a24);
  a24=-9.7041986999999998e-11;
  a24=(a21?a24:0);
  a35=-5.4879706200000003e-09;
  a35=(a33?a35:0);
  a24=(a24+a35);
  a24=(a24*a36);
  a30=(a30+a24);
  a24=1.6820099199999999e-14;
  a21=(a21?a24:0);
  a24=1.7719781700000000e-12;
  a33=(a33?a24:0);
  a21=(a21+a33);
  a21=(a21*a37);
  a30=(a30+a21);
  a31=(a31*a30);
  a31=(a31*a28);
  a01=(a01+a31);
  a29=(a01-a29);
  a01=(a01/a29);
  a29=(a01-a26);
  a29=(a29/a07);
  a31=8.3333333333333331e-05;
  a28=8.0000000000000004e-01;
  a30=2.7999999999999998e+00;
  a21=2.1490977393394096e-02;
  a37=pow(a09,a28);
  a21=(a21*a37);
  a37=-5.3000000000000003e-01;
  a37=pow(a05,a37);
  a21=(a21*a37);
  a37=1.9418333333333333e+01;
  a33=5.0000000000000003e-02;
  a24=5.8171812816840792e-06;
  a36=1.3108110000000001e+05;
  a35=1.3300000000000001e+00;
  a06=pow(a06,a35);
  a36=(a36*a06);
  a36=(a09-a36);
  a24=(a24*a36);
  a33=(a33*a24);
  a37=(a37+a33);
  a37=pow(a37,a28);
  a21=(a21*a37);
  a30=(a30*a21);
  a21=1.1334031413612566e-02;
  a37=2.5444024061585990e-01;
  a33=4.7750000000000001e-02;
  a24=3.9999999999999996e+00;
  a24=(a24-a15);
  a36=2.9999999999999996e+00;
  a06=1.1111111111111113e-01;
  a06=(a06*a18);
  a06=(a26-a06);
  a06=sqrt(a06);
  a36=(a36*a06);
  a24=(a24-a36);
  a33=(a33*a24);
  a37=(a37*a33);
  a21=(a21+a37);
  a30=(a30*a21);
  a21=4.7454482412149287e+02;
  a21=(a21-a05);
  a30=(a30*a21);
  a28=(a28*a30);
  a28=(a31*a28);
  a30=2.0876637060343724e-11;
  a21=1000000.;
  a37=12000.;
  a13=(a13/a37);
  a33=5.0000000000000001e-04;
  a24=1.0000000000000000e-03;
  a36=3.1099999999999999e-03;
  a06=4000000.;
  a06=(a09/a06);
  a36=(a36/a06);
  a18=2.2400000000000000e-01;
  a20=(a20/a18);
  a36=(a36/a20);
  a18=4.5100000000000000e-12;
  a35=21079.;
  a35=(a35/a05);
  a35=exp(a35);
  a18=(a18*a35);
  a18=(a36+a18);
  a36=(a36/a18);
  a18=1.2499999999999999e-07;
  a35=-1.0500000000000000e+00;
  a06=pow(a06,a35);
  a18=(a18*a06);
  a06=-1.5000000000000000e+00;
  a20=pow(a20,a06);
  a18=(a18*a20);
  a20=15813.;
  a20=(a20/a05);
  a20=exp(a20);
  a18=(a18*a20);
  a18=(a36*a18);
  a36=(a26-a36);
  a20=1.0900000000000000e-08;
  a06=13188.;
  a06=(a06/a05);
  a06=exp(a06);
  a20=(a20*a06);
  a36=(a36*a20);
  a18=(a18+a36);
  a18=(a24*a18);
  a36=2.5000000000000001e-04;
  a18=(a18+a36);
  a18=(a18-a24);
  a18=(a18/a24);
  a36=(a18+a26);
  a36=casadi_sq(a36);
  a36=(a19+a36);
  a36=sqrt(a36);
  a18=(a18-a26);
  a18=casadi_sq(a18);
  a18=(a19+a18);
  a18=sqrt(a18);
  a36=(a36-a18);
  a33=(a33*a36);
  a33=(a33+a24);
  a13=(a13-a33);
  a13=(a21*a13);
  a24=arg[0]? arg[0][0] : 0;
  a24=(a12*a24);
  a24=(a24+a14);
  a24=(a24/a37);
  a24=(a21*a24);
  a36=55.;
  a24=(a24+a36);
  a18=(a13-a24);
  a20=casadi_sq(a18);
  a06=500.;
  a20=(a20+a06);
  a20=sqrt(a20);
  a20=(a20+a18);
  a20=casadi_sq(a20);
  a05=5.5786748793512579e-02;
  a35=2.0930000000000000e+00;
  a27=700.;
  a00=arg[0]? arg[0][2] : 0;
  a00=(a27*a00);
  a32=100.;
  a00=(a00+a32);
  a34=6.6730000000000004e+01;
  a00=(a00-a34);
  a38=casadi_sq(a00);
  a38=(a38+a26);
  a38=sqrt(a38);
  a38=(a03*a38);
  a00=(a03*a00);
  a38=(a38+a00);
  a38=(a35*a38);
  a00=(a05*a38);
  a39=5.0103928944824938e-01;
  a00=(a00/a39);
  a40=830.;
  a41=9.0477868423386053e-08;
  a42=4.7592649022342260e+02;
  a43=1.4050000000000000e+00;
  a44=9.3010000000000004e-01;
  a45=2.7439999999999999e-02;
  a46=(a38-a12);
  a47=casadi_sq(a46);
  a47=(a47+a26);
  a47=sqrt(a47);
  a47=(a03*a47);
  a46=(a03*a46);
  a47=(a47+a46);
  a47=(a47+a12);
  a47=(a19*a47);
  a46=-3.6759999999999998e-01;
  a47=pow(a47,a46);
  a47=(a45*a47);
  a47=(a44-a47);
  a47=(a43*a47);
  a48=8.4087818972735737e-03;
  a49=(a47+a48);
  a50=1.0000000000000000e-02;
  a47=(a47-a48);
  a47=casadi_sq(a47);
  a47=(a50+a47);
  a47=sqrt(a47);
  a49=(a49+a47);
  a49=(a03*a49);
  a49=(a42*a49);
  a49=(a41*a49);
  a49=(a40*a49);
  a49=(a02*a49);
  a49=(a49-a00);
  a47=casadi_sq(a49);
  a47=(a47+a50);
  a47=sqrt(a47);
  a47=(a03*a47);
  a00=(a00-a47);
  a49=(a03*a49);
  a00=(a00+a49);
  a49=1.6701309648274978e-01;
  a47=(a00/a49);
  a18=(a18-a47);
  a47=casadi_sq(a18);
  a47=(a47+a06);
  a47=sqrt(a47);
  a47=(a47+a18);
  a47=casadi_sq(a47);
  a20=(a20-a47);
  a20=(a30*a20);
  a47=4.1753274120687449e-11;
  a24=(a24+a38);
  a18=3.3402619296549957e-01;
  a51=(a00/a18);
  a24=(a24-a51);
  a24=(a13-a24);
  a52=casadi_sq(a24);
  a52=(a52+a06);
  a52=sqrt(a52);
  a52=(a52+a24);
  a52=casadi_sq(a52);
  a24=(a24-a51);
  a51=casadi_sq(a24);
  a51=(a51+a06);
  a51=sqrt(a51);
  a51=(a51+a24);
  a51=casadi_sq(a51);
  a52=(a52-a51);
  a52=(a47*a52);
  a20=(a20-a52);
  a52=arg[0]? arg[0][1] : 0;
  a52=(a12*a52);
  a52=(a52+a14);
  a52=(a52/a37);
  a21=(a21*a52);
  a21=(a21+a36);
  a36=(a13-a21);
  a52=casadi_sq(a36);
  a52=(a52+a06);
  a52=sqrt(a52);
  a52=(a52+a36);
  a52=casadi_sq(a52);
  a37=arg[0]? arg[0][3] : 0;
  a27=(a27*a37);
  a27=(a27+a32);
  a27=(a27-a34);
  a34=casadi_sq(a27);
  a34=(a34+a26);
  a34=sqrt(a34);
  a34=(a03*a34);
  a27=(a03*a27);
  a34=(a34+a27);
  a35=(a35*a34);
  a05=(a05*a35);
  a05=(a05/a39);
  a39=(a35-a12);
  a34=casadi_sq(a39);
  a34=(a34+a26);
  a34=sqrt(a34);
  a34=(a03*a34);
  a39=(a03*a39);
  a34=(a34+a39);
  a34=(a34+a12);
  a19=(a19*a34);
  a19=pow(a19,a46);
  a45=(a45*a19);
  a44=(a44-a45);
  a43=(a43*a44);
  a44=(a43+a48);
  a43=(a43-a48);
  a43=casadi_sq(a43);
  a43=(a50+a43);
  a43=sqrt(a43);
  a44=(a44+a43);
  a44=(a03*a44);
  a42=(a42*a44);
  a41=(a41*a42);
  a40=(a40*a41);
  a02=(a02*a40);
  a02=(a02-a05);
  a40=casadi_sq(a02);
  a40=(a40+a50);
  a40=sqrt(a40);
  a40=(a03*a40);
  a05=(a05-a40);
  a02=(a03*a02);
  a05=(a05+a02);
  a49=(a05/a49);
  a36=(a36-a49);
  a49=casadi_sq(a36);
  a49=(a49+a06);
  a49=sqrt(a49);
  a49=(a49+a36);
  a49=casadi_sq(a49);
  a52=(a52-a49);
  a30=(a30*a52);
  a21=(a21+a35);
  a18=(a05/a18);
  a21=(a21-a18);
  a13=(a13-a21);
  a21=casadi_sq(a13);
  a21=(a21+a06);
  a21=sqrt(a21);
  a21=(a21+a13);
  a21=casadi_sq(a21);
  a13=(a13-a18);
  a18=casadi_sq(a13);
  a18=(a18+a06);
  a18=sqrt(a18);
  a18=(a18+a13);
  a18=casadi_sq(a18);
  a21=(a21-a18);
  a47=(a47*a21);
  a30=(a30-a47);
  a20=(a20+a30);
  a20=(a25*a20);
  a20=(a20-a22);
  a31=(a31*a20);
  a22=3800.;
  a30=-2.0000000000000003e+05;
  a47=2.7999999999999998e-04;
  a33=(a33-a47);
  a30=(a30*a33);
  a30=exp(a30);
  a30=(a26+a30);
  a22=(a22/a30);
  a33=2070.;
  a30=(1./a30);
  a30=(a26-a30);
  a33=(a33*a30);
  a22=(a22+a33);
  a31=(a31*a22);
  a22=5.2700000000000002e-04;
  a22=(a22*a30);
  a20=(a20*a22);
  a26=(a26-a20);
  a31=(a31/a26);
  a26=(a03*a31);
  a20=1.0000000000000000e-08;
  a31=casadi_sq(a31);
  a20=(a20+a31);
  a20=sqrt(a20);
  a20=(a03*a20);
  a26=(a26+a20);
  a28=(a28+a26);
  a29=(a29*a28);
  a01=(a01*a09);
  a09=-5.0000000000000000e-01;
  a10=pow(a10,a09);
  a10=(a10*a17);
  a10=(a10*a15);
  a17=(a17+a10);
  a08=(a08*a17);
  a11=(a11*a08);
  a11=(a11/a16);
  a01=(a01*a11);
  a01=(a01/a07);
  a29=(a29-a01);
  a29=(a29/a04);
  if (res[0]!=0) res[0][1]=a29;
  a29=1.0000000000000001e-09;
  a38=(a38*a00);
  a04=8.9813315936869049e+00;
  a00=casadi_sq(a00);
  a00=(a03*a00);
  a00=(a04*a00);
  a38=(a38-a00);
  a38=(a29*a38);
  a35=(a35*a05);
  a05=casadi_sq(a05);
  a03=(a03*a05);
  a04=(a04*a03);
  a35=(a35-a04);
  a29=(a29*a35);
  a38=(a38+a29);
  a25=(a25*a38);
  a38=2000.;
  a25=(a25/a38);
  a23=(a23-a25);
  if (res[0]!=0) res[0][2]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
