/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};
static const casadi_int casadi_s4[22] = 
  {10, 5, 0, 1, 4, 9, 11, 14,
  6, 4, 5, 9, 4, 5, 7, 8,
  9, 2, 3, 0, 1, 2};
static const casadi_int casadi_s5[3] = {5, 0, 1};

/* ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt:(i0[10],i1[0],i2[0],i3)->(o0[5],o1[10x5,14nz],o2[5x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100;
  a000=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][0]=a000;
  a000=5.0000000000000000e-01;
  a001=10000000.;
  a002=arg[0]? arg[0][4] : 0;
  a002=(a001*a002);
  a003=1.0486488000000000e+05;
  a004=5.2214244335811971e-04;
  a005=3.1741935483870970e-05;
  a006=2.4600000000000002e-04;
  a007=4.;
  a008=8.9999999999999982e+00;
  a009=3.1415926535897931e+00;
  a010=70.;
  a011=arg[0]? arg[0][9] : 0;
  a011=(a010*a011);
  a012=-20.;
  a011=(a011+a012);
  a011=(a009*a011);
  a012=180.;
  a011=(a011/a012);
  a012=sin(a011);
  a013=casadi_sq(a012);
  a008=(a008-a013);
  a008=sqrt(a008);
  a007=(a007-a008);
  a011=cos(a011);
  a007=(a007-a011);
  a007=(a006*a007);
  a005=(a005+a007);
  a004=(a004/a005);
  a007=1.3999999999999999e+00;
  a013=pow(a004,a007);
  a013=(a003*a013);
  a002=(a002-a013);
  a014=(a000*a002);
  a015=9.9999999999999995e-07;
  a016=casadi_sq(a002);
  a016=(a015+a016);
  a016=sqrt(a016);
  a017=(a000*a016);
  a014=(a014+a017);
  a014=(a014+a013);
  a013=(a014*a005);
  a017=4.7265673220362294e-04;
  a018=3.1998800000000001e-02;
  a019=-1.5475000000000001e+01;
  a020=3.8520879710794719e+02;
  a021=1000.;
  a022=arg[0]? arg[0][5] : 0;
  a022=(a021*a022);
  a023=7.7041759421589438e+02;
  a022=(a022-a023);
  a022=(a022/a023);
  a024=1.;
  a025=(a022+a024);
  a026=casadi_sq(a025);
  a026=(a015+a026);
  a026=sqrt(a026);
  a022=(a022-a024);
  a027=casadi_sq(a022);
  a027=(a015+a027);
  a027=sqrt(a027);
  a028=(a026-a027);
  a028=(a020*a028);
  a028=(a028+a023);
  a023=42600000.;
  a028=(a028/a023);
  a023=1.4856437000000003e-01;
  a023=(a028/a023);
  a029=(a019*a023);
  a029=(a018*a029);
  a030=1.2729341902076080e-04;
  a029=(a029+a030);
  a030=(a017+a029);
  a031=4.4009600000000003e-02;
  a032=1.0800000000000001e+01;
  a033=(a032*a023);
  a033=(a031*a033);
  a034=1.5573144458581126e-05;
  a033=(a033+a034);
  a030=(a030+a033);
  a034=1.8015200000000002e-02;
  a035=9.3499999999999996e+00;
  a023=(a035*a023);
  a023=(a034*a023);
  a036=5.5189420533618726e-06;
  a023=(a023+a036);
  a030=(a030+a023);
  a036=2.9678653787116167e+02;
  a017=(a017/a030);
  a037=(a036*a017);
  a038=2.5982224333412501e+02;
  a029=(a029/a030);
  a039=(a038*a029);
  a037=(a037+a039);
  a039=1.8891332800116336e+02;
  a033=(a033/a030);
  a040=(a039*a033);
  a037=(a037+a040);
  a040=4.6149917847151289e+02;
  a023=(a023/a030);
  a041=(a040*a023);
  a037=(a037+a041);
  a041=(a030*a037);
  a042=(a013/a041);
  a043=(a042/a021);
  if (res[0]!=0) res[0][1]=a043;
  a043=1000000.;
  a044=arg[0]? arg[0][8] : 0;
  a044=(a015*a044);
  a045=(a000*a044);
  a046=1.0000000000000001e-20;
  a047=casadi_sq(a044);
  a046=(a046+a047);
  a046=sqrt(a046);
  a047=(a000*a046);
  a045=(a045+a047);
  a045=(a043*a045);
  a047=2.8796878496782119e+02;
  a048=6.2104223773632675e-04;
  a049=1.1363636363636365e+00;
  a050=1.4310260600938740e+01;
  a028=(a050*a028);
  a028=(a049*a028);
  a028=(a048-a028);
  a028=(a047*a028);
  a051=arg[0]? arg[0][7] : 0;
  a051=(a021*a051);
  a052=(a028*a051);
  a052=(a052/a014);
  a053=(a005-a052);
  a053=(a043*a053);
  a054=(a045*a053);
  a055=8.3140000000000001e+00;
  a056=(a055*a042);
  a013=(a013/a056);
  a054=(a054/a013);
  a057=(a054/a021);
  if (res[0]!=0) res[0][2]=a057;
  a057=2.3291751145757966e-01;
  a058=1.0000000000000001e-09;
  a059=2.0930000000000000e+00;
  a060=700.;
  a061=arg[0]? arg[0][2] : 0;
  a061=(a060*a061);
  a062=100.;
  a061=(a061+a062);
  a063=6.6730000000000004e+01;
  a061=(a061-a063);
  a064=casadi_sq(a061);
  a064=(a064+a024);
  a064=sqrt(a064);
  a065=(a000*a064);
  a066=(a000*a061);
  a065=(a065+a066);
  a065=(a059*a065);
  a066=5.5786748793512579e-02;
  a067=(a066*a065);
  a068=5.0103928944824938e-01;
  a067=(a067/a068);
  a069=830.;
  a070=9.0477868423386053e-08;
  a071=4.7592649022342260e+02;
  a072=1.4050000000000000e+00;
  a073=9.3010000000000004e-01;
  a074=2.7439999999999999e-02;
  a075=(a065-a010);
  a076=casadi_sq(a075);
  a076=(a076+a024);
  a076=sqrt(a076);
  a077=(a000*a076);
  a078=(a000*a075);
  a077=(a077+a078);
  a077=(a077+a010);
  a077=(a015*a077);
  a078=-3.6759999999999998e-01;
  a079=pow(a077,a078);
  a079=(a074*a079);
  a079=(a073-a079);
  a079=(a072*a079);
  a080=8.4087818972735737e-03;
  a081=(a079+a080);
  a082=1.0000000000000000e-02;
  a079=(a079-a080);
  a083=casadi_sq(a079);
  a083=(a082+a083);
  a083=sqrt(a083);
  a081=(a081+a083);
  a081=(a000*a081);
  a081=(a071*a081);
  a081=(a070*a081);
  a081=(a069*a081);
  a081=(a021*a081);
  a081=(a081-a067);
  a084=casadi_sq(a081);
  a084=(a084+a082);
  a084=sqrt(a084);
  a085=(a000*a084);
  a067=(a067-a085);
  a085=(a000*a081);
  a067=(a067+a085);
  a085=(a065*a067);
  a086=8.9813315936869049e+00;
  a087=casadi_sq(a067);
  a087=(a000*a087);
  a087=(a086*a087);
  a085=(a085-a087);
  a085=(a058*a085);
  a087=arg[0]? arg[0][3] : 0;
  a087=(a060*a087);
  a087=(a087+a062);
  a087=(a087-a063);
  a063=casadi_sq(a087);
  a063=(a063+a024);
  a063=sqrt(a063);
  a062=(a000*a063);
  a088=(a000*a087);
  a062=(a062+a088);
  a062=(a059*a062);
  a088=(a066*a062);
  a088=(a088/a068);
  a068=(a062-a010);
  a089=casadi_sq(a068);
  a089=(a089+a024);
  a089=sqrt(a089);
  a090=(a000*a089);
  a091=(a000*a068);
  a090=(a090+a091);
  a090=(a090+a010);
  a090=(a015*a090);
  a091=pow(a090,a078);
  a091=(a074*a091);
  a073=(a073-a091);
  a073=(a072*a073);
  a091=(a073+a080);
  a073=(a073-a080);
  a080=casadi_sq(a073);
  a080=(a082+a080);
  a080=sqrt(a080);
  a091=(a091+a080);
  a091=(a000*a091);
  a091=(a071*a091);
  a091=(a070*a091);
  a091=(a069*a091);
  a091=(a021*a091);
  a091=(a091-a088);
  a092=casadi_sq(a091);
  a092=(a092+a082);
  a092=sqrt(a092);
  a082=(a000*a092);
  a088=(a088-a082);
  a082=(a000*a091);
  a088=(a088+a082);
  a082=(a062*a088);
  a093=casadi_sq(a088);
  a093=(a000*a093);
  a086=(a086*a093);
  a082=(a082-a086);
  a058=(a058*a082);
  a085=(a085+a058);
  a085=(a050*a085);
  a057=(a057*a085);
  a057=(a057/a048);
  a048=2.0496741008267014e-01;
  a057=(a057/a048);
  if (res[0]!=0) res[0][3]=a057;
  a057=arg[0]? arg[0][1] : 0;
  a048=arg[0]? arg[0][0] : 0;
  a057=(a057-a048);
  a048=360.;
  a085=3.3333333333333336e+01;
  a058=arg[3]? arg[3][0] : 0;
  a058=(a065+a058);
  a085=(a085*a058);
  a048=(a048*a085);
  a048=(a015*a048);
  a048=(a048/a010);
  a057=(a057-a048);
  if (res[0]!=0) res[0][4]=a057;
  if (res[1]!=0) res[1][0]=a024;
  a002=(a002+a002);
  a057=1.0000000000000000e-03;
  a048=(a057/a041);
  a085=(a005*a048);
  a058=(a000*a085);
  a016=(a016+a016);
  a082=(a058/a016);
  a082=(a002*a082);
  a086=(a082+a058);
  a086=(a001*a086);
  if (res[1]!=0) res[1][1]=a086;
  a086=1.2979973556000717e-03;
  a025=(a025+a025);
  a093=2.3474178403755869e-08;
  a094=6.7310890222197948e+00;
  a023=(a023/a030);
  a042=(a042/a041);
  a095=(a057*a042);
  a096=(a030*a095);
  a097=(a040*a096);
  a098=(a023*a097);
  a095=(a037*a095);
  a098=(a098-a095);
  a033=(a033/a030);
  a095=(a039*a096);
  a099=(a033*a095);
  a098=(a098+a099);
  a029=(a029/a030);
  a099=(a038*a096);
  a100=(a029*a099);
  a098=(a098+a100);
  a017=(a017/a030);
  a096=(a036*a096);
  a096=(a017*a096);
  a098=(a098+a096);
  a097=(a097/a030);
  a097=(a098-a097);
  a097=(a034*a097);
  a097=(a035*a097);
  a095=(a095/a030);
  a095=(a098-a095);
  a095=(a031*a095);
  a095=(a032*a095);
  a097=(a097+a095);
  a099=(a099/a030);
  a098=(a098-a099);
  a098=(a018*a098);
  a098=(a019*a098);
  a097=(a097+a098);
  a097=(a094*a097);
  a097=(a093*a097);
  a097=(a020*a097);
  a026=(a026+a026);
  a098=(a097/a026);
  a098=(a025*a098);
  a098=(a086*a098);
  a022=(a022+a022);
  a027=(a027+a027);
  a097=(a097/a027);
  a097=(a022*a097);
  a097=(a086*a097);
  a098=(a098-a097);
  a098=(a021*a098);
  if (res[1]!=0) res[1][2]=a098;
  a098=5.5555555555555558e-03;
  a048=(a014*a048);
  a048=(a006*a048);
  a097=(a012*a048);
  a099=(a012+a012);
  a008=(a008+a008);
  a048=(a048/a008);
  a048=(a099*a048);
  a048=(a011*a048);
  a097=(a097+a048);
  a097=(a098*a097);
  a097=(a009*a097);
  a048=(a004/a005);
  a095=3.9999999999999991e-01;
  a004=pow(a004,a095);
  a007=(a007*a004);
  a085=(a085-a082);
  a085=(a085-a058);
  a085=(a003*a085);
  a085=(a007*a085);
  a085=(a048*a085);
  a085=(a006*a085);
  a058=(a012*a085);
  a085=(a085/a008);
  a085=(a099*a085);
  a085=(a011*a085);
  a058=(a058+a085);
  a058=(a098*a058);
  a058=(a009*a058);
  a097=(a097-a058);
  a097=(a010*a097);
  if (res[1]!=0) res[1][3]=a097;
  a052=(a052/a014);
  a097=(a057/a013);
  a045=(a045*a097);
  a045=(a043*a045);
  a052=(a052*a045);
  a054=(a054/a013);
  a057=(a057*a054);
  a054=(a057/a056);
  a058=(a005*a054);
  a052=(a052-a058);
  a013=(a013/a056);
  a013=(a013*a057);
  a055=(a055*a013);
  a041=(a055/a041);
  a005=(a005*a041);
  a052=(a052+a005);
  a005=(a000*a052);
  a016=(a005/a016);
  a002=(a002*a016);
  a016=(a002+a005);
  a001=(a001*a016);
  if (res[1]!=0) res[1][4]=a001;
  a001=(a045/a014);
  a051=(a051*a001);
  a047=(a047*a051);
  a049=(a049*a047);
  a050=(a050*a049);
  a050=(a093*a050);
  a042=(a042*a055);
  a055=(a030*a042);
  a040=(a040*a055);
  a023=(a023*a040);
  a037=(a037*a042);
  a023=(a023-a037);
  a039=(a039*a055);
  a033=(a033*a039);
  a023=(a023+a033);
  a038=(a038*a055);
  a029=(a029*a038);
  a023=(a023+a029);
  a036=(a036*a055);
  a017=(a017*a036);
  a023=(a023+a017);
  a040=(a040/a030);
  a040=(a023-a040);
  a034=(a034*a040);
  a035=(a035*a034);
  a039=(a039/a030);
  a039=(a023-a039);
  a031=(a031*a039);
  a032=(a032*a031);
  a035=(a035+a032);
  a038=(a038/a030);
  a023=(a023-a038);
  a018=(a018*a023);
  a019=(a019*a018);
  a035=(a035+a019);
  a094=(a094*a035);
  a093=(a093*a094);
  a050=(a050+a093);
  a020=(a020*a050);
  a026=(a020/a026);
  a025=(a025*a026);
  a025=(a086*a025);
  a020=(a020/a027);
  a022=(a022*a020);
  a086=(a086*a022);
  a025=(a025-a086);
  a025=(a021*a025);
  if (res[1]!=0) res[1][5]=a025;
  a028=(a028*a001);
  a028=(a021*a028);
  a028=(-a028);
  if (res[1]!=0) res[1][6]=a028;
  a044=(a044+a044);
  a053=(a053*a097);
  a043=(a043*a053);
  a043=(a000*a043);
  a046=(a046+a046);
  a046=(a043/a046);
  a044=(a044*a046);
  a044=(a044+a043);
  a044=(a015*a044);
  if (res[1]!=0) res[1][7]=a044;
  a054=(a014*a054);
  a045=(a045-a054);
  a014=(a014*a041);
  a045=(a045+a014);
  a045=(a006*a045);
  a014=(a012*a045);
  a045=(a045/a008);
  a045=(a099*a045);
  a045=(a011*a045);
  a014=(a014+a045);
  a014=(a098*a014);
  a014=(a009*a014);
  a052=(a052-a002);
  a052=(a052-a005);
  a003=(a003*a052);
  a007=(a007*a003);
  a048=(a048*a007);
  a006=(a006*a048);
  a012=(a012*a006);
  a006=(a006/a008);
  a099=(a099*a006);
  a011=(a011*a099);
  a012=(a012+a011);
  a098=(a098*a012);
  a009=(a009*a098);
  a014=(a014-a009);
  a010=(a010*a014);
  if (res[1]!=0) res[1][8]=a010;
  a010=2.6184466668591010e-05;
  a014=(a010*a067);
  a009=-1.3675999999999999e+00;
  a077=pow(a077,a009);
  a077=(a078*a077);
  a079=(a079+a079);
  a098=-1.1758568887722907e-04;
  a067=(a067+a067);
  a067=(a098*a067);
  a065=(a010*a065);
  a067=(a067+a065);
  a065=(a000*a067);
  a081=(a081+a081);
  a084=(a084+a084);
  a084=(a065/a084);
  a081=(a081*a084);
  a084=(a065-a081);
  a084=(a021*a084);
  a084=(a069*a084);
  a084=(a070*a084);
  a084=(a071*a084);
  a084=(a000*a084);
  a083=(a083+a083);
  a083=(a084/a083);
  a079=(a079*a083);
  a079=(a079+a084);
  a079=(a072*a079);
  a079=(a074*a079);
  a077=(a077*a079);
  a077=(a015*a077);
  a077=(a000*a077);
  a014=(a014-a077);
  a075=(a075+a075);
  a076=(a076+a076);
  a077=(a077/a076);
  a075=(a075*a077);
  a014=(a014-a075);
  a075=1.9958514652637567e+00;
  a067=(a067-a065);
  a067=(a067+a081);
  a067=(a075*a067);
  a067=(a066*a067);
  a014=(a014+a067);
  a014=(a059*a014);
  a014=(a000*a014);
  a061=(a061+a061);
  a064=(a064+a064);
  a067=(a014/a064);
  a067=(a061*a067);
  a014=(a014+a067);
  a014=(a060*a014);
  if (res[1]!=0) res[1][9]=a014;
  a014=(a010*a088);
  a090=pow(a090,a009);
  a078=(a078*a090);
  a073=(a073+a073);
  a088=(a088+a088);
  a098=(a098*a088);
  a010=(a010*a062);
  a098=(a098+a010);
  a010=(a000*a098);
  a091=(a091+a091);
  a092=(a092+a092);
  a092=(a010/a092);
  a091=(a091*a092);
  a092=(a010-a091);
  a021=(a021*a092);
  a069=(a069*a021);
  a070=(a070*a069);
  a071=(a071*a070);
  a071=(a000*a071);
  a080=(a080+a080);
  a080=(a071/a080);
  a073=(a073*a080);
  a073=(a073+a071);
  a072=(a072*a073);
  a074=(a074*a072);
  a078=(a078*a074);
  a015=(a015*a078);
  a015=(a000*a015);
  a014=(a014-a015);
  a068=(a068+a068);
  a089=(a089+a089);
  a015=(a015/a089);
  a068=(a068*a015);
  a014=(a014-a068);
  a098=(a098-a010);
  a098=(a098+a091);
  a075=(a075*a098);
  a066=(a066*a075);
  a014=(a014+a066);
  a059=(a059*a014);
  a000=(a000*a059);
  a087=(a087+a087);
  a063=(a063+a063);
  a063=(a000/a063);
  a087=(a087*a063);
  a000=(a000+a087);
  a000=(a060*a000);
  if (res[1]!=0) res[1][10]=a000;
  a000=-1.;
  if (res[1]!=0) res[1][11]=a000;
  if (res[1]!=0) res[1][12]=a024;
  a024=-1.7940000000000000e-04;
  a064=(a024/a064);
  a061=(a061*a064);
  a024=(a024+a061);
  a060=(a060*a024);
  if (res[1]!=0) res[1][13]=a060;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
