/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ECO_opt_2inj_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* ECO_opt_2inj_expl_ode_fun:(i0[6],i1[4],i2[0])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=2.9678653787116167e+02;
  a01=1000.;
  a02=5.0000000000000000e-01;
  a03=10000000.;
  a04=arg[0]? arg[0][0] : 0;
  a04=(a03*a04);
  a05=1.0486488000000000e+05;
  a06=5.2214244335811971e-04;
  a07=3.1741935483870970e-05;
  a08=2.4600000000000002e-04;
  a09=4.;
  a10=8.9999999999999982e+00;
  a11=3.1415926535897931e+00;
  a12=70.;
  a13=arg[0]? arg[0][5] : 0;
  a13=(a12*a13);
  a14=-20.;
  a13=(a13+a14);
  a15=(a11*a13);
  a16=180.;
  a15=(a15/a16);
  a17=sin(a15);
  a18=casadi_sq(a17);
  a10=(a10-a18);
  a19=sqrt(a10);
  a09=(a09-a19);
  a15=cos(a15);
  a09=(a09-a15);
  a09=(a08*a09);
  a07=(a07+a09);
  a06=(a06/a07);
  a09=1.3999999999999999e+00;
  a09=pow(a06,a09);
  a05=(a05*a09);
  a04=(a04-a05);
  a09=(a02*a04);
  a19=9.9999999999999995e-07;
  a04=casadi_sq(a04);
  a04=(a19+a04);
  a04=sqrt(a04);
  a04=(a02*a04);
  a09=(a09+a04);
  a09=(a09+a05);
  a05=(a09*a07);
  a04=4.7265673220362294e-04;
  a20=3.1998800000000001e-02;
  a21=-1.5475000000000001e+01;
  a22=3.8520879710794719e+02;
  a23=arg[0]? arg[0][1] : 0;
  a23=(a01*a23);
  a24=7.7041759421589438e+02;
  a23=(a23-a24);
  a23=(a23/a24);
  a25=1.;
  a26=(a23+a25);
  a26=casadi_sq(a26);
  a26=(a19+a26);
  a26=sqrt(a26);
  a23=(a23-a25);
  a23=casadi_sq(a23);
  a23=(a19+a23);
  a23=sqrt(a23);
  a26=(a26-a23);
  a22=(a22*a26);
  a22=(a22+a24);
  a24=42600000.;
  a26=(a22/a24);
  a23=1.4856437000000003e-01;
  a23=(a26/a23);
  a21=(a21*a23);
  a20=(a20*a21);
  a21=1.2729341902076080e-04;
  a20=(a20+a21);
  a21=(a04+a20);
  a27=4.4009600000000003e-02;
  a28=1.0800000000000001e+01;
  a28=(a28*a23);
  a27=(a27*a28);
  a28=1.5573144458581126e-05;
  a27=(a27+a28);
  a21=(a21+a27);
  a28=1.8015200000000002e-02;
  a29=9.3499999999999996e+00;
  a29=(a29*a23);
  a28=(a28*a29);
  a29=5.5189420533618726e-06;
  a28=(a28+a29);
  a21=(a21+a28);
  a04=(a04/a21);
  a29=(a00*a04);
  a23=2.5982224333412501e+02;
  a20=(a20/a21);
  a30=(a23*a20);
  a29=(a29+a30);
  a30=1.8891332800116336e+02;
  a27=(a27/a21);
  a31=(a30*a27);
  a29=(a29+a31);
  a31=4.6149917847151289e+02;
  a28=(a28/a21);
  a32=(a31*a28);
  a29=(a29+a32);
  a32=(a21*a29);
  a05=(a05/a32);
  a32=(a01<a05);
  a33=2.9266399999999999e+00;
  a33=(a32?a33:0);
  a34=(!a32);
  a35=3.2986770000000001e+00;
  a35=(a34?a35:0);
  a33=(a33+a35);
  a35=1.4879768000000001e-03;
  a35=(a32?a35:0);
  a36=1.4082404000000000e-03;
  a36=(a34?a36:0);
  a35=(a35+a36);
  a35=(a35*a05);
  a33=(a33+a35);
  a35=-5.6847600000000001e-07;
  a35=(a32?a35:0);
  a36=-3.9632219999999998e-06;
  a36=(a34?a36:0);
  a35=(a35+a36);
  a36=casadi_sq(a05);
  a35=(a35*a36);
  a33=(a33+a35);
  a35=1.0097038000000000e-10;
  a35=(a32?a35:0);
  a37=5.6415150000000002e-09;
  a37=(a34?a37:0);
  a35=(a35+a37);
  a37=(a05*a36);
  a35=(a35*a37);
  a33=(a33+a35);
  a35=-6.7533509999999998e-15;
  a35=(a32?a35:0);
  a38=-2.4448539999999999e-12;
  a38=(a34?a38:0);
  a35=(a35+a38);
  a38=casadi_sq(a36);
  a35=(a35*a38);
  a33=(a33+a35);
  a00=(a00*a33);
  a00=(a00*a04);
  a04=3.2825378399999998e+00;
  a04=(a32?a04:0);
  a33=3.7824563599999999e+00;
  a33=(a34?a33:0);
  a04=(a04+a33);
  a33=1.4830875399999999e-03;
  a33=(a32?a33:0);
  a35=-2.9967341599999998e-03;
  a35=(a34?a35:0);
  a33=(a33+a35);
  a33=(a33*a05);
  a04=(a04+a33);
  a33=-7.5796666899999999e-07;
  a33=(a32?a33:0);
  a35=9.8473020100000000e-06;
  a35=(a34?a35:0);
  a33=(a33+a35);
  a33=(a33*a36);
  a04=(a04+a33);
  a33=2.0947055499999999e-10;
  a33=(a32?a33:0);
  a35=-9.6812950900000007e-09;
  a35=(a34?a35:0);
  a33=(a33+a35);
  a33=(a33*a37);
  a04=(a04+a33);
  a33=-2.1671779399999999e-14;
  a33=(a32?a33:0);
  a35=3.2437283700000000e-12;
  a35=(a34?a35:0);
  a33=(a33+a35);
  a33=(a33*a38);
  a04=(a04+a33);
  a23=(a23*a04);
  a23=(a23*a20);
  a00=(a00+a23);
  a23=3.8574602900000001e+00;
  a23=(a32?a23:0);
  a04=2.3567735200000000e+00;
  a04=(a34?a04:0);
  a23=(a23+a04);
  a04=4.4143702599999998e-03;
  a04=(a32?a04:0);
  a33=8.9845967700000005e-03;
  a33=(a34?a33:0);
  a04=(a04+a33);
  a04=(a04*a05);
  a23=(a23+a04);
  a04=-2.2148140400000001e-06;
  a04=(a32?a04:0);
  a33=-7.1235626899999998e-06;
  a33=(a34?a33:0);
  a04=(a04+a33);
  a04=(a04*a36);
  a23=(a23+a04);
  a04=5.2349018800000005e-10;
  a04=(a32?a04:0);
  a33=2.4591902199999998e-09;
  a33=(a34?a33:0);
  a04=(a04+a33);
  a04=(a04*a37);
  a23=(a23+a04);
  a04=-4.7208416400000003e-14;
  a04=(a32?a04:0);
  a33=-1.4369954799999999e-13;
  a33=(a34?a33:0);
  a04=(a04+a33);
  a04=(a04*a38);
  a23=(a23+a04);
  a30=(a30*a23);
  a30=(a30*a27);
  a00=(a00+a30);
  a30=3.0339924900000002e+00;
  a30=(a32?a30:0);
  a27=4.1986405600000003e+00;
  a27=(a34?a27:0);
  a30=(a30+a27);
  a27=2.1769180400000002e-03;
  a27=(a32?a27:0);
  a23=-2.0364341000000002e-03;
  a23=(a34?a23:0);
  a27=(a27+a23);
  a27=(a27*a05);
  a30=(a30+a27);
  a27=-1.6407251799999999e-07;
  a27=(a32?a27:0);
  a23=6.5204021099999997e-06;
  a23=(a34?a23:0);
  a27=(a27+a23);
  a27=(a27*a36);
  a30=(a30+a27);
  a27=-9.7041986999999998e-11;
  a27=(a32?a27:0);
  a36=-5.4879706200000003e-09;
  a36=(a34?a36:0);
  a27=(a27+a36);
  a27=(a27*a37);
  a30=(a30+a27);
  a27=1.6820099199999999e-14;
  a32=(a32?a27:0);
  a27=1.7719781700000000e-12;
  a34=(a34?a27:0);
  a32=(a32+a34);
  a32=(a32*a38);
  a30=(a30+a32);
  a31=(a31*a30);
  a31=(a31*a28);
  a00=(a00+a31);
  a29=(a00-a29);
  a00=(a00/a29);
  a29=(a00-a25);
  a31=(a29/a07);
  a28=8.3333333333333331e-05;
  a30=8.0000000000000004e-01;
  a32=2.7999999999999998e+00;
  a38=2.1490977393394096e-02;
  a34=pow(a09,a30);
  a38=(a38*a34);
  a34=-5.3000000000000003e-01;
  a34=pow(a05,a34);
  a38=(a38*a34);
  a34=1.9418333333333333e+01;
  a27=5.0000000000000003e-02;
  a37=5.8171812816840792e-06;
  a36=1.3108110000000001e+05;
  a23=1.3300000000000001e+00;
  a06=pow(a06,a23);
  a36=(a36*a06);
  a36=(a09-a36);
  a37=(a37*a36);
  a27=(a27*a37);
  a34=(a34+a27);
  a34=pow(a34,a30);
  a38=(a38*a34);
  a32=(a32*a38);
  a38=1.1334031413612566e-02;
  a34=2.5444024061585990e-01;
  a27=4.7750000000000001e-02;
  a37=3.9999999999999996e+00;
  a37=(a37-a15);
  a36=2.9999999999999996e+00;
  a06=1.1111111111111113e-01;
  a06=(a06*a18);
  a06=(a25-a06);
  a06=sqrt(a06);
  a36=(a36*a06);
  a37=(a37-a36);
  a27=(a27*a37);
  a34=(a34*a27);
  a38=(a38+a34);
  a32=(a32*a38);
  a38=4.7454482412149287e+02;
  a38=(a38-a05);
  a32=(a32*a38);
  a30=(a30*a32);
  a30=(a28*a30);
  a32=2.0876637060343724e-11;
  a38=1000000.;
  a34=12000.;
  a13=(a13/a34);
  a27=5.0000000000000001e-04;
  a37=1.0000000000000000e-03;
  a36=3.1099999999999999e-03;
  a06=4000000.;
  a06=(a09/a06);
  a36=(a36/a06);
  a18=2.2400000000000000e-01;
  a20=(a20/a18);
  a36=(a36/a20);
  a18=4.5100000000000000e-12;
  a23=21079.;
  a23=(a23/a05);
  a23=exp(a23);
  a18=(a18*a23);
  a18=(a36+a18);
  a36=(a36/a18);
  a18=1.2499999999999999e-07;
  a23=-1.0500000000000000e+00;
  a06=pow(a06,a23);
  a18=(a18*a06);
  a06=-1.5000000000000000e+00;
  a20=pow(a20,a06);
  a18=(a18*a20);
  a20=15813.;
  a20=(a20/a05);
  a20=exp(a20);
  a18=(a18*a20);
  a18=(a36*a18);
  a36=(a25-a36);
  a20=1.0900000000000000e-08;
  a06=13188.;
  a06=(a06/a05);
  a06=exp(a06);
  a20=(a20*a06);
  a36=(a36*a20);
  a18=(a18+a36);
  a18=(a37*a18);
  a36=2.5000000000000001e-04;
  a18=(a18+a36);
  a18=(a18-a37);
  a18=(a18/a37);
  a36=(a18+a25);
  a36=casadi_sq(a36);
  a36=(a19+a36);
  a36=sqrt(a36);
  a18=(a18-a25);
  a18=casadi_sq(a18);
  a18=(a19+a18);
  a18=sqrt(a18);
  a36=(a36-a18);
  a27=(a27*a36);
  a27=(a27+a37);
  a13=(a13-a27);
  a13=(a38*a13);
  a37=arg[1]? arg[1][0] : 0;
  a37=(a12*a37);
  a37=(a37+a14);
  a37=(a37/a34);
  a37=(a38*a37);
  a36=55.;
  a37=(a37+a36);
  a18=(a13-a37);
  a20=casadi_sq(a18);
  a06=500.;
  a20=(a20+a06);
  a20=sqrt(a20);
  a20=(a20+a18);
  a20=casadi_sq(a20);
  a23=5.5786748793512579e-02;
  a04=2.0930000000000000e+00;
  a33=700.;
  a35=arg[1]? arg[1][2] : 0;
  a35=(a33*a35);
  a39=100.;
  a35=(a35+a39);
  a40=6.6730000000000004e+01;
  a35=(a35-a40);
  a41=casadi_sq(a35);
  a41=(a41+a25);
  a41=sqrt(a41);
  a41=(a02*a41);
  a35=(a02*a35);
  a41=(a41+a35);
  a41=(a04*a41);
  a35=(a23*a41);
  a42=5.0103928944824938e-01;
  a35=(a35/a42);
  a43=830.;
  a44=9.0477868423386053e-08;
  a45=4.7592649022342260e+02;
  a46=1.4050000000000000e+00;
  a47=9.3010000000000004e-01;
  a48=2.7439999999999999e-02;
  a49=(a41-a12);
  a50=casadi_sq(a49);
  a50=(a50+a25);
  a50=sqrt(a50);
  a50=(a02*a50);
  a49=(a02*a49);
  a50=(a50+a49);
  a50=(a50+a12);
  a50=(a19*a50);
  a49=-3.6759999999999998e-01;
  a50=pow(a50,a49);
  a50=(a48*a50);
  a50=(a47-a50);
  a50=(a46*a50);
  a51=8.4087818972735737e-03;
  a52=(a50+a51);
  a53=1.0000000000000000e-02;
  a50=(a50-a51);
  a50=casadi_sq(a50);
  a50=(a53+a50);
  a50=sqrt(a50);
  a52=(a52+a50);
  a52=(a02*a52);
  a52=(a45*a52);
  a52=(a44*a52);
  a52=(a43*a52);
  a52=(a01*a52);
  a52=(a52-a35);
  a50=casadi_sq(a52);
  a50=(a50+a53);
  a50=sqrt(a50);
  a50=(a02*a50);
  a35=(a35-a50);
  a52=(a02*a52);
  a35=(a35+a52);
  a52=1.6701309648274978e-01;
  a50=(a35/a52);
  a18=(a18-a50);
  a50=casadi_sq(a18);
  a50=(a50+a06);
  a50=sqrt(a50);
  a50=(a50+a18);
  a50=casadi_sq(a50);
  a20=(a20-a50);
  a20=(a32*a20);
  a50=4.1753274120687449e-11;
  a37=(a37+a41);
  a18=3.3402619296549957e-01;
  a54=(a35/a18);
  a37=(a37-a54);
  a37=(a13-a37);
  a55=casadi_sq(a37);
  a55=(a55+a06);
  a55=sqrt(a55);
  a55=(a55+a37);
  a55=casadi_sq(a55);
  a37=(a37-a54);
  a54=casadi_sq(a37);
  a54=(a54+a06);
  a54=sqrt(a54);
  a54=(a54+a37);
  a54=casadi_sq(a54);
  a55=(a55-a54);
  a55=(a50*a55);
  a20=(a20-a55);
  a55=arg[1]? arg[1][1] : 0;
  a55=(a12*a55);
  a55=(a55+a14);
  a55=(a55/a34);
  a55=(a38*a55);
  a55=(a55+a36);
  a36=(a13-a55);
  a34=casadi_sq(a36);
  a34=(a34+a06);
  a34=sqrt(a34);
  a34=(a34+a36);
  a34=casadi_sq(a34);
  a14=arg[1]? arg[1][3] : 0;
  a33=(a33*a14);
  a33=(a33+a39);
  a33=(a33-a40);
  a40=casadi_sq(a33);
  a40=(a40+a25);
  a40=sqrt(a40);
  a40=(a02*a40);
  a33=(a02*a33);
  a40=(a40+a33);
  a04=(a04*a40);
  a23=(a23*a04);
  a23=(a23/a42);
  a42=(a04-a12);
  a40=casadi_sq(a42);
  a40=(a40+a25);
  a40=sqrt(a40);
  a40=(a02*a40);
  a42=(a02*a42);
  a40=(a40+a42);
  a40=(a40+a12);
  a40=(a19*a40);
  a40=pow(a40,a49);
  a48=(a48*a40);
  a47=(a47-a48);
  a46=(a46*a47);
  a47=(a46+a51);
  a46=(a46-a51);
  a46=casadi_sq(a46);
  a46=(a53+a46);
  a46=sqrt(a46);
  a47=(a47+a46);
  a47=(a02*a47);
  a45=(a45*a47);
  a44=(a44*a45);
  a43=(a43*a44);
  a43=(a01*a43);
  a43=(a43-a23);
  a44=casadi_sq(a43);
  a44=(a44+a53);
  a44=sqrt(a44);
  a44=(a02*a44);
  a23=(a23-a44);
  a43=(a02*a43);
  a23=(a23+a43);
  a52=(a23/a52);
  a36=(a36-a52);
  a52=casadi_sq(a36);
  a52=(a52+a06);
  a52=sqrt(a52);
  a52=(a52+a36);
  a52=casadi_sq(a52);
  a34=(a34-a52);
  a32=(a32*a34);
  a55=(a55+a04);
  a18=(a23/a18);
  a55=(a55-a18);
  a13=(a13-a55);
  a55=casadi_sq(a13);
  a55=(a55+a06);
  a55=sqrt(a55);
  a55=(a55+a13);
  a55=casadi_sq(a55);
  a13=(a13-a18);
  a18=casadi_sq(a13);
  a18=(a18+a06);
  a18=sqrt(a18);
  a18=(a18+a13);
  a18=casadi_sq(a18);
  a55=(a55-a18);
  a50=(a50*a55);
  a32=(a32-a50);
  a20=(a20+a32);
  a20=(a24*a20);
  a20=(a20-a22);
  a32=(a28*a20);
  a50=3800.;
  a55=-2.0000000000000003e+05;
  a18=2.7999999999999998e-04;
  a27=(a27-a18);
  a55=(a55*a27);
  a55=exp(a55);
  a55=(a25+a55);
  a50=(a50/a55);
  a27=2070.;
  a55=(1./a55);
  a55=(a25-a55);
  a27=(a27*a55);
  a50=(a50+a27);
  a32=(a32*a50);
  a50=5.2700000000000002e-04;
  a50=(a50*a55);
  a20=(a20*a50);
  a20=(a25-a20);
  a32=(a32/a20);
  a20=(a02*a32);
  a50=1.0000000000000000e-08;
  a32=casadi_sq(a32);
  a50=(a50+a32);
  a50=sqrt(a50);
  a50=(a02*a50);
  a20=(a20+a50);
  a30=(a30+a20);
  a31=(a31*a30);
  a30=(a00*a09);
  a50=-5.0000000000000000e-01;
  a10=pow(a10,a50);
  a10=(a10*a17);
  a10=(a10*a15);
  a17=(a17+a10);
  a08=(a08*a17);
  a11=(a11*a08);
  a11=(a11/a16);
  a30=(a30*a11);
  a30=(a30/a07);
  a31=(a31-a30);
  a03=(a31/a03);
  if (res[0]!=0) res[0][0]=a03;
  a20=(a20/a01);
  if (res[0]!=0) res[0][1]=a20;
  a20=(a09*a11);
  a03=4.9200000000000003e-04;
  a20=(a20/a03);
  a20=(a20/a38);
  if (res[0]!=0) res[0][2]=a20;
  a20=2.2500000000000003e-02;
  a38=1.0000000000000001e-09;
  a41=(a41*a35);
  a03=8.9813315936869049e+00;
  a35=casadi_sq(a35);
  a35=(a02*a35);
  a35=(a03*a35);
  a41=(a41-a35);
  a41=(a38*a41);
  a04=(a04*a23);
  a23=casadi_sq(a23);
  a23=(a02*a23);
  a03=(a03*a23);
  a04=(a04-a03);
  a38=(a38*a04);
  a41=(a41+a38);
  a41=(a24*a41);
  a41=(a22/a41);
  a38=5.5000000000000000e-02;
  a04=(a41-a38);
  a03=4.5000000000000005e-02;
  a04=(a04/a03);
  a03=(a04+a25);
  a03=casadi_sq(a03);
  a03=(a19+a03);
  a03=sqrt(a03);
  a04=(a04-a25);
  a04=casadi_sq(a04);
  a04=(a19+a04);
  a04=sqrt(a04);
  a03=(a03-a04);
  a20=(a20*a03);
  a20=(a20+a38);
  a20=(a20-a53);
  a38=9.0000000000000011e-02;
  a20=(a20/a38);
  a38=(a25-a20);
  a03=(a31/a09);
  a04=(a11/a07);
  a04=(a03+a04);
  a04=(a05*a04);
  a38=(a38*a04);
  a04=2.;
  a23=(a05/a04);
  a35=(a23/a04);
  a30=arg[0]? arg[0][3] : 0;
  a30=(a01*a30);
  a16=(a30-a23);
  a16=(a16/a23);
  a08=(a16+a25);
  a08=casadi_sq(a08);
  a08=(a19+a08);
  a08=sqrt(a08);
  a16=(a16-a25);
  a16=casadi_sq(a16);
  a16=(a19+a16);
  a16=sqrt(a16);
  a08=(a08-a16);
  a35=(a35*a08);
  a35=(a35+a23);
  a03=(a03*a35);
  a03=(a03*a29);
  a03=(a03/a00);
  a03=(a20*a03);
  a38=(a38+a03);
  a38=(a38/a01);
  if (res[0]!=0) res[0][3]=a38;
  a38=3.0000000000000002e-02;
  a41=(a41-a38);
  a01=2.0000000000000000e-02;
  a41=(a41/a01);
  a01=(a41+a25);
  a01=casadi_sq(a01);
  a01=(a19+a01);
  a01=sqrt(a01);
  a41=(a41-a25);
  a41=casadi_sq(a41);
  a41=(a19+a41);
  a41=sqrt(a41);
  a01=(a01-a41);
  a01=(a53*a01);
  a01=(a01+a38);
  a01=(a01-a53);
  a53=4.0000000000000001e-02;
  a01=(a01/a53);
  a04=(a04*a01);
  a53=14700000000000.;
  a38=425.;
  a05=(a05-a35);
  a20=(a20*a05);
  a05=2.4750000000000000e-01;
  a41=1.7261659773794022e+01;
  a41=(a41*a22);
  a24=(a24*a21);
  a24=(a24+a22);
  a41=(a41/a24);
  a24=5.0500000000000000e-01;
  a41=(a41-a24);
  a22=4.9500000000000000e-01;
  a41=(a41/a22);
  a22=(a41+a25);
  a22=casadi_sq(a22);
  a22=(a19+a22);
  a22=sqrt(a22);
  a41=(a41-a25);
  a41=casadi_sq(a41);
  a41=(a19+a41);
  a41=sqrt(a41);
  a22=(a22-a41);
  a05=(a05*a22);
  a05=(a05+a24);
  a20=(a20/a05);
  a20=(a20+a35);
  a35=2450.;
  a05=(a20-a35);
  a24=850.;
  a05=(a05/a24);
  a24=(a05+a25);
  a24=casadi_sq(a24);
  a24=(a19+a24);
  a24=sqrt(a24);
  a05=(a05-a25);
  a05=casadi_sq(a05);
  a05=(a19+a05);
  a05=sqrt(a05);
  a24=(a24-a05);
  a38=(a38*a24);
  a38=(a38+a35);
  a35=2.9999999999999999e-01;
  a35=pow(a38,a35);
  a53=(a53*a35);
  a35=-3.7885874600000003e+04;
  a35=(a35/a38);
  a35=exp(a35);
  a53=(a53*a35);
  a35=-6.3685135334380902e+01;
  a24=4.5158125676954798e-02;
  a24=(a24*a38);
  a35=(a35+a24);
  a24=-1.2515899044340800e-05;
  a05=casadi_sq(a38);
  a24=(a24*a05);
  a35=(a35+a24);
  a24=1.2761063410490901e-09;
  a22=(a38*a05);
  a24=(a24*a22);
  a35=(a35+a24);
  a35=exp(a35);
  a53=(a53*a35);
  a35=-2.1616775267765301e-01;
  a24=-1.4150677727192500e-04;
  a24=(a24*a38);
  a35=(a35+a24);
  a24=8.0613583815391402e-08;
  a24=(a24*a05);
  a35=(a35+a24);
  a24=-1.5492924459827299e-11;
  a24=(a24*a22);
  a35=(a35+a24);
  a35=exp(a35);
  a53=(a53*a35);
  a35=(a19*a09);
  a24=8.3140000000000001e+00;
  a24=(a24*a20);
  a35=(a35/a24);
  a24=casadi_sq(a35);
  a53=(a53*a24);
  a04=(a04*a53);
  a20=arg[0]? arg[0][4] : 0;
  a20=(a19*a20);
  a41=(a02*a20);
  a21=1.0000000000000001e-20;
  a20=casadi_sq(a20);
  a21=(a21+a20);
  a21=sqrt(a21);
  a02=(a02*a21);
  a41=(a41+a02);
  a02=-3.4406106632446999e+01;
  a21=2.3494934456157100e-02;
  a21=(a21*a38);
  a02=(a02+a21);
  a21=-6.4128703247252901e-06;
  a21=(a21*a05);
  a02=(a02+a21);
  a21=6.3511193233658496e-10;
  a21=(a21*a22);
  a02=(a02+a21);
  a02=exp(a02);
  a02=(a02*a35);
  a02=(a41/a02);
  a35=casadi_sq(a02);
  a35=(a25-a35);
  a04=(a04*a35);
  a35=6400000000.;
  a35=(a35*a38);
  a21=-3.1631692830000002e+03;
  a21=(a21/a38);
  a21=exp(a21);
  a35=(a35*a21);
  a21=-9.3599480447577406e+01;
  a20=6.3558292509131406e-02;
  a20=(a20*a38);
  a21=(a21+a20);
  a20=-1.7863654436551200e-05;
  a20=(a20*a05);
  a21=(a21+a20);
  a20=1.8638945288587902e-09;
  a20=(a20*a22);
  a21=(a21+a20);
  a21=exp(a21);
  a35=(a35*a21);
  a20=-3.3643138140046602e+01;
  a03=2.2765700445381100e-02;
  a03=(a03*a38);
  a20=(a20+a03);
  a03=-6.0418949566370099e-06;
  a03=(a03*a05);
  a20=(a20+a03);
  a03=5.6857726302647499e-10;
  a03=(a03*a22);
  a20=(a20+a03);
  a20=exp(a20);
  a35=(a35*a20);
  a35=(a35*a24);
  a20=38000000000000.;
  a20=(a20*a21);
  a21=-3.8912988534365702e+01;
  a03=2.6973990690595199e-02;
  a03=(a03*a38);
  a21=(a21+a03);
  a03=-7.4066732123685597e-06;
  a03=(a03*a05);
  a21=(a21+a03);
  a03=7.4221250079953700e-10;
  a03=(a03*a22);
  a21=(a21+a03);
  a21=exp(a21);
  a20=(a20*a21);
  a20=(a20*a24);
  a35=(a35+a20);
  a53=(a53/a35);
  a02=(a02*a53);
  a25=(a25+a02);
  a04=(a04/a25);
  a28=(a28*a04);
  a41=(a01*a41);
  a04=2.8796878496782119e+02;
  a25=6.2104223773632675e-04;
  a02=1.1363636363636365e+00;
  a53=1.4310260600938740e+01;
  a53=(a53*a26);
  a02=(a02*a53);
  a25=(a25-a02);
  a04=(a04*a25);
  a04=(a04*a30);
  a04=(a04/a09);
  a31=(a31*a04);
  a30=1.3895275153002993e+00;
  a31=(a31/a30);
  a31=(a31/a09);
  a11=(a11+a31);
  a01=(a01*a11);
  a41=(a41*a01);
  a07=(a07-a04);
  a41=(a41/a07);
  a28=(a28-a41);
  a28=(a28/a19);
  if (res[0]!=0) res[0][4]=a28;
  a28=1.4285714285714285e-02;
  if (res[0]!=0) res[0][5]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ECO_opt_2inj_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int ECO_opt_2inj_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ECO_opt_2inj_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ECO_opt_2inj_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ECO_opt_2inj_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ECO_opt_2inj_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
